### ISSUE TITLE
marketplace will be empty if github configuration is missing

### ISSUE THREAD

**Issue by DongZhaoYu** [Microsoft/pai#1536]
when deploy new release, if user don't add the configuration
github-owner
github-repository
github-path

restserver can be deployed correctly but the marketplace will show nothing.

**Comment by Gerhut** [comment]
Environment variables is set as

```yaml
GITHUB_OWNER: None 
GITHUB_REPOSITORY: None 
GITHUB_PATH: None 
```
