### ISSUE TITLE
 Web cannot be displayed

### ISSUE THREAD

**Issue by 111Moderato** [Microsoft/pai#2151]
I used a single box deployment. 
When Running Commands:
`sudo python paictl.py cluster k8s-bootup  -p pai-config`
A warning will appear halfway: **The connection to the server ***.***.***.***:8080 was refused - did you specify the right host or port?**
But in the end it will show:
**[INFO] - deployment.confStorage.synchronization : Cluster Configuration synchronization from external storage is successful.**
However, I can't access Kubernetes Dashboard. (http://<master>:9090)

And the web http://***.***.***:8080, show :
![image](https://user-images.githubusercontent.com/28188655/52898279-c2c6f980-3216-11e9-8727-093981741f54.png)

**OpenPAI Environment**:
- OpenPAI version: v0.9.0
- OS (e.g. from /etc/os-release): Ubuntu16.04

**Comment by ydye** [comment]
1) Login to your master node. And execute the command following and then paste the result.
```
sudo docker ps -a

sudo docker logs kubelet
```

**Comment by 111Moderato** [comment]
sudo docker ps -a:
[ps.txt](https://github.com/Microsoft/pai/files/2873803/ps.txt)
sudo docker logs kubelet:
[log.txt](https://github.com/Microsoft/pai/files/2873804/log.txt)
@ydye

**Comment by ydye** [comment]
1: Execute the command and show us the result:
```
kubectl get deployment -n kube-system | grep dashboard
```

2: Paste the log of paictl's error.log and info.log. Ip may appear in these files, you should remove them.

**Comment by 111Moderato** [comment]
1.
![image](https://user-images.githubusercontent.com/28188655/52924657-98855100-3368-11e9-9fb8-1e1654d5405c.png)
2.
[errors.log](https://github.com/Microsoft/pai/files/2873828/errors.log)
[info.log](https://github.com/Microsoft/pai/files/2873829/info.log)
@ydye

**Comment by ydye** [comment]
Have you config this?  https://github.com/Microsoft/pai/blob/pai-0.9.y/examples/cluster-configuration/cluster-configuration.yaml#L62

**Comment by 111Moderato** [comment]
yes
![image](https://user-images.githubusercontent.com/28188655/52925820-04b68380-336e-11e9-9e67-c494cead5bc0.png)

**Comment by ydye** [comment]
```
 kubectl describe deployment kubernetes-dashboard  -n kube-system

```

**Comment by ydye** [comment]
And dashboard has a resource requirement.
```
        resources:
          # the ideal cpu setting will be 3.5, according to our experiment. If the server hosting k8s dashboard has enough resource, user can change this setting to a larger value.
          requests:
            cpu: "1000m"
            memory: 1000Mi
```
