### ISSUE TITLE
[Job Debugging] Provide detail information when the job container exits.

### ISSUE THREAD

**Issue by ydye** [microsoft/pai#2218]
**What would you like to be added**:
```
Sometimes, users' job may be kill by OpenPAI due to several reasons. It's different from
the users' error. We can class these error as system error. And the container can't be reserved 
if it's failed due to system error. So more detailed log should be provided. So that users could know the reason why their job container exits and can't be reserverd for job debugging. 

An example of system error which will make your job failed:
    - Disk pressure

```
**Why is this needed**:

```
If the job container can't be reserved if it failed due to system error. Users may feel confused. 
```
**Without this feature, how does the current module work**：
```
User should investigate the job log.
```
**Components that may involve changes**:
```
TBD
```

**Comment by Binyang2014** [comment]
refer to kubernetes/kubernetes#140

**Comment by Binyang2014** [comment]
This item will work on K8S version. Several tasks:
- [ ] Map the docker exit info mechanism from dockerScript to kube runtime
- [ ] Reorganize the error spec. Remove yarn error, add new error type for k8s version

**Comment by Binyang2014** [comment]
Add failurePattern for runtime:
```yaml
- errorType: user/system
  patterns:
    pattenExitCode:
      exitCode: 132
      userLog: ""
      runtimeLog: ""
      # more can be added here
    pattenUserLog:
      userLog: "This is an error"
  matches: ${pattens.pattenExitCode} or ${pattens.pattenUserLog}
  reason: 'User program terminated by SIGILL'
  solution: 'Please check the log and retry again'
  containerExitCode: 132
```
