### ISSUE TITLE
Can Not Start Hadoop-node-manager 

### ISSUE THREAD

**Issue by Wenbo93** [Microsoft/pai#253]
File information - nodelabel.mirror
![screenshot from 2018-01-23 11-39-21](https://user-images.githubusercontent.com/24285637/35257057-217f9a8a-0032-11e8-832d-a5d8c3160aab.png)

The host_config['ip'] is not rendered.

**Comment by ydye** [comment]
Can you provide us the examples of infra-node ( starting namenode and resourcemanager ) and worker-node ( starting datanode and nodemanager ) in your cluster-configuration?

**Comment by xwzheng1020** [comment]
1. 
[datanode-hdfs-site.xml.txt](https://github.com/Microsoft/pai/files/1655135/datanode-hdfs-site.xml.txt)
[namenode-hdfs-site.xml.txt](https://github.com/Microsoft/pai/files/1655136/namenode-hdfs-site.xml.txt)
[nodemanager-yarn-site.xml.txt](https://github.com/Microsoft/pai/files/1655137/nodemanager-yarn-site.xml.txt)
[resourcemanager-yarn-site.xml.txt](https://github.com/Microsoft/pai/files/1655138/resourcemanager-yarn-site.xml.txt)
There are no ip in these files.

2. The host-configuration.yaml like this:
```
master:
    ip: 192.168.1.83
    dataFolder: /mnt
    zkid: "1"
    hdfsrole: master
    yarnrole: master
    zookeeper: "true"
    jobhistory: "true"
    launcher: "true"
    restserver: "true"
    webportal: "true"
    

worker-01:
    ip: 192.168.1.41
    dataFolder: /mnt
    machinetype: gpu
    hdfsrole: worker
    yarnrole: worker
```

3. In the pod of hadoop-name-node-ds, we can put and get files using "$HADOOPHOME/bin/hdfs dfs get(or put) ..." , but the files can not be downloaded through hadoop web portal(http://ip:50070). The same state of {{host_config['ip']}}.

@ydye
