### ISSUE TITLE
NVIDIA Driver with IB ERROR summary

### ISSUE THREAD

**Issue by qzwlinux** [Microsoft/pai#2638]
**Organization Name**: SitonHoly

**can not install nvidia driver**:
Now we have 9 SitonHoly server machine,one IB switch and one Storage
We deployment pai cluster use dev-box:v0.10.1
k8s cluster installed successful
when we use ` python ./paictl.py service start `
it was stay in drivers-one-shot
    v0.10.1  drivers-one-shot IB can not install
    v0.11.0  drivers-one-shot IB can install
    v0.12.0  drivers-one-shot IB can install
then i use v0.12.0 drivers-one-shot.

In computer node drivers-one-shot can work,
but in master (master have 0 nvidia-card) it fail to work and it restart always
![image](https://user-images.githubusercontent.com/46511491/56554045-03e6db80-65c3-11e9-99a5-72c4f304f3a5.png)

Finally by modify ` /pai/src/drivers/deploy/drivers.yaml.template`  line 35,  I deployment v0.10.1 passed
![image](https://user-images.githubusercontent.com/46511491/56555939-051b0700-65c9-11e9-85f6-40bfe06f140f.png)

 deployment related issues: v0.10.1
Operating type: Initial deployment

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: v0.10.1
- Cloud provider or hardware configuration: SitonHoly Server Machine
- OS (e.g. from /etc/os-release): Ubuntu 16.04.5 LTS
- Kernel (e.g. `uname -a`): .4.0-131-generic
-Hardware (e.g. core number, memory size, storage size, GPU type etc.):
  master:  
    mem: 125G
      gpu:
      type: generic
      count: 0
    cpu:
      vcore: 32
    os: ubuntu16.04

  node[1~7]:
    mem: 376G
    gpu:
      type: gtx1080ti
      count: 10
    cpu:
      vcore: 32
    os: ubuntu16.04

  node[8~9]:
    mem: 376G
    gpu:
      type: v100
      count: 10
    cpu:
      vcore: 32
    os: ubuntu16.04

  IB switch : MSX6025
  H3C switch : S5120V2
- Others:  none

**Comment by qzwlinux** [comment]
![image](https://user-images.githubusercontent.com/46511491/56561516-ee30e080-65d9-11e9-982a-8646d0178e54.png)

i think this opinion is error reason,Master node have a IB card but not have nvidia card

**Comment by abuccts** [comment]
Hi @qzwlinux,

Could  you share your configuration files? Please replace sensitive information with masks.
The `drivers` pod should be started on worker nodes only, not the master node.

/cc @ydye @hao1939

**Comment by qzwlinux** [comment]
@abuccts i don't know how to off master driver install. 
configuration will send here on 20:00

**Comment by abuccts** [comment]
I mean in [`layout.yaml` configuration](https://github.com/Microsoft/pai/blob/master/examples/cluster-configuration/layout.yaml#L49), if the machine is set as `pai-master: true`, then drivers pod won't be started on that node. Only machines with `pai-worker: true` run drivers pod.

**Comment by qzwlinux** [comment]
- layout.yaml

```
kubernetes:
  api-servers-url: http://master:8080
  dashboard-url: http://master:9090

# TODO please modify it according to your own hardware
machine-sku:
  master:
    mem: 125G
#    gpu:
#      type: generic
#      count: 0
    cpu:
      vcore: 32
    os: ubuntu16.04

  node1:
    mem: 376G
    gpu:
      type: v100
      count: 10
    cpu:
      vcore: 32
    os: ubuntu16.04

  node2:
    mem: 376G
    gpu:
      type: gtx1080ti
      count: 10
    cpu:
      vcore: 32
    os: ubuntu16.04

  node5:
    mem: 376G
    gpu:
      type: gtx1080ti
      count: 10
    cpu:
      vcore: 32
    os: ubuntu16.04

  node6:
    mem: 376G
    gpu:
      type: v100
      count: 10
    cpu:
      vcore: 32
    os: ubuntu16.04

  node7:
    mem: 376G
    gpu:
      type: gtx1080ti
      count: 10
    cpu:
      vcore: 32
    os: ubuntu16.04

  node8:
    mem: 376G
    gpu:
      type: gtx1080ti
      count: 10
    cpu:
      vcore: 32
    os: ubuntu16.04

  node9:
    mem: 376G
    gpu:
      type: gtx1080ti
      count: 10
    cpu:
      vcore: 32
    os: ubuntu16.04

machine-list:
  - dashboard: "true"
    docker-data: "/var/lib/docker"
    etcdid: "etcdid1"
    hostip: "master"
    hostname: "master"
    k8s-role: "master"
    machine-type: "master"
    nodename: "master"
    pai-master: "true"
    password: "******"
    ssh-port: "22"
    username: "root"
    zkid: "1"

  - docker-data: "/var/lib/docker"
    hostip: "node1"
    hostname: "sdu1"
    k8s-role: "worker"
    machine-type: "node1"
    nodename: "node1"
    pai-worker: "true"
    password: "******"
    ssh-port: "22"
    username: "root"

  - docker-data: "/var/lib/docker"
    hostip: "node2"
    hostname: "sdu2"
    k8s-role: "worker"
    machine-type: "node2"
    nodename: "node2"
    pai-worker: "true"
    password: "******"
    ssh-port: "22"
    username: "root"

  - docker-data: "/var/lib/docker"
    hostip: "node5"
    hostname: "sdu5"
    k8s-role: "worker"
    machine-type: "node5"
    nodename: "node5"
    pai-worker: "true"
    password: "******"
    ssh-port: "22"
    username: "root"


  - docker-data: "/var/lib/docker"
    hostip: "node6"
    hostname: "sdu6"
    k8s-role: "worker"
    machine-type: "node6"
    nodename: "node6"
    pai-worker: "true"
    password: "******"
    ssh-port: "22"
    username: "root"

  - docker-data: "/var/lib/docker"
    hostip: "node7"
    hostname: "sdu7"
    k8s-role: "worker"
    machine-type: "node7"
    nodename: "node7"
    pai-worker: "true"
    password: "******"
    ssh-port: "22"
    username: "root"

  - docker-data: "/var/lib/docker"
    hostip: "node8"
    hostname: "sdu8"
    k8s-role: "worker"
    machine-type: "node8"
    nodename: "node8"
    pai-worker: "true"
    password: "******"
    ssh-port: "22"
    username: "root"

  - docker-data: "/var/lib/docker"
    hostip: "node9"
    hostname: "sdu9"
    k8s-role: "worker"
    machine-type: "node9"
    nodename: "node9"
    pai-worker: "true"
    password: "******"
    ssh-port: "22"
    username: "root"
```

**Comment by qzwlinux** [comment]
- services-configuration.yaml

```
cluster:
  common:
    cluster-id: cluster
  #
  #  # HDFS, zookeeper data path on your cluster machine.
    data-path: "/datastorage"

  # the docker registry to store docker images that contain system services like frameworklauncher, hadoop, etc.
  docker-registry:

    # The namespace in your registry. If the registry is docker.io, the namespace will be your user account.
    namespace: openpai

    # E.g., gcr.io.
    # if the registry is hub.docker, please fill this value with docker.io
    domain: docker.io
    # If the docker registry doesn't require authentication, please comment username and password
    #username: <username>
    #password: <password>

    tag: v0.10.1

    # The name of the secret in kubernetes will be created in your cluster
    # Must be lower case, e.g., regsecret.
    secret-name: pai-secret


#Uncomment following lines if you want to customize yarn
#hadoop-resource-manager:
#  # job log retain time
#  yarn_log_retain_seconds: 2592000
#  # port for yarn exporter
#  yarn_exporter_port: 9459


#Uncomment following lines if you want to customize hdfs
hadoop-data-node:
#  # storage path for hdfs, support comma-delimited list of directories, eg. /path/to/folder1,/path/to/folder2 ...
#  # if left empty, will use cluster.common.data-path/hdfs/data
  storage_path: /datastorage/data1,/datastorage/data2,/datastorage/data3

# uncomment following if you want to change customeize yarn-frameworklauncher
#yarn-frameworklauncher:
#  frameworklauncher-port: 9086


rest-server:
  # database admin username
  default-pai-admin-username: admin
  # database admin password
  default-pai-admin-password: ******


# uncomment following section if you want to customize the port of web portal
# webportal:
#   server-port: 9286

# uncomment following if you want to change customeize grafana
# grafana:
#   port: 3000

# uncomment following if you want to change customeize drivers
drivers:
  set-nvidia-runtime: true
#  # You can set drivers version here. If this value is miss, default value will be 384.111
#  # Current supported version list
#  # 384.111
#  # 390.25
#  # 410.73
  version: "410.73"

# uncomment following if you want node-exporter listen to different port
# node-exporter:
#   port: 9100

# uncomment following if you want to customeize job-exporter
# job-exporter:
#   port: 9102
#   logging-level: INFO
#   interface: eth0,eno2

# if you want to enable alert manager to send alert email, uncomment following lines and fill
# the right values.
# alert-manager:
#   receiver: your_addr@example.com
#   smtp_url: smtp.office365.com:587
#   smtp_from: alert_sender@example.com
#   smtp_auth_username: alert_sender@example.com
#   smtp_auth_password: password_for_alert_sender
#   port: 9093 # this is optional, you should not write this if you do not want to change the port alert-manager is listening on

# uncomment following if you want to change customeize prometheus
# prometheus:
#   port: 9091
#   # How frequently to scrape targets
#   scrape_interval: 30
#
#   # if you want to use key file to login nodes
#   

# uncomment following section if you want to customize the port of pylon
# pylon:
#  port: 80

# uncomment following section if you want to customize the threshold of cleaner
# cleaner:
#  threshold: 94
#  interval: 60
                       
```

**Comment by qzwlinux** [comment]
- kubernetes-configuration.yaml
```
kubernetes:
  # Find the namesever in  /etc/resolv.conf
  cluster-dns: 192.168.1.1
  # To support k8s ha, you should set an lb address here.
  # If deploy k8s with single master node, please set master IP address here
  load-balance-ip: master

  # specify an IP range not in the same network segment with the host machine.
  service-cluster-ip-range: 10.254.0.0/16
  # According to the etcdversion, you should fill a corresponding backend name.
  # If you are not familiar with etcd, please don't change it.
  storage-backend: etcd3
  # The docker registry used in the k8s deployment. If you can access to gcr, we suggest to use gcr.
  docker-registry: docker.io/mirrorgooglecontainers
  # http://gcr.io/google_containers/hyperkube. Or the tag in your registry.
  hyperkube-version: v1.9.9
  # http://gcr.io/google_containers/etcd. Or the tag in your registry.
  # If you are not familiar with etcd, please don't change it.
  etcd-version: 3.2.17
  # http://gcr.io/google_containers/kube-apiserver. Or the tag in your registry.
  apiserver-version: v1.9.9
  # http://gcr.io/google_containers/kube-scheduler. Or the tag in your registry.
  kube-scheduler-version: v1.9.9
  # http://gcr.io/google_containers/kube-controller-manager
  kube-controller-manager-version:  v1.9.9
  # http://gcr.io/google_containers/kubernetes-dashboard-amd64
  dashboard-version: v1.8.3
  # The path to storage etcd data.
  etcd-data-path: "/var/etcd"

  # #Enable QoS feature for k8s or not. Default value is "true"
  # qos-switch: "true"

```
