### ISSUE TITLE
Parsing of data-path in services-configuration.yaml may wrong?

### ISSUE THREAD

**Issue by ICEORY** [microsoft/pai#3278]
**OpenPAI version**： 0.11.0
**Issues**: If I set data-path to "/datastorage1,/datastorage2", the actual storage path of HDFS will be "/datastorage1,/datastorage2" and "/datastorage2", instead of "/datastorage1" and "/datastorage2"

**Comment by mzmssg** [comment]
Could you share yaml snippet, including global `data-path` and datanode `storage_path`?

**Comment by ICEORY** [comment]
- data-path
```
cluster:
  common:
  #  cluster-id: pai-example
  #
  #  # HDFS, zookeeper data path on your cluster machine.
    data-path: "/datastorage,/ssd/datastorage"
```

- storage_path
```
#Uncomment following lines if you want to customize hdfs
#hadoop-data-node:
#  # storage path for hdfs, support comma-delimited list of directories, eg. /path/to/folder1,/path/to/folder2 ...
#  # if left empty, will use cluster.common.data-path/hdfs/data
#  storage_path:
```

**Comment by mzmssg** [comment]
@ICEORY 
We don't support comma-delimited path in common.data-path, if you would like to customize hdfs storage path, please move it to data-node.storage_path.
- data-path
```
cluster:
  common:
  #  cluster-id: pai-example
  #
  #  # HDFS, zookeeper data path on your cluster machine.
    data-path: "/datastorage"
```

- storage_path
```
#Uncomment following lines if you want to customize hdfs
hadoop-data-node:
  # storage path for hdfs, support comma-delimited list of directories, eg. /path/to/folder1,/path/to/folder2 ...
  # if left empty, will use cluster.common.data-path/hdfs/data
  storage_path: "/datastorage,/ssd/datastorage"
```
