### ISSUE TITLE
Add log-type parameter to webportal config to support different log types

### ISSUE THREAD

**Issue by wangdian** [microsoft/pai#3315]
Add parameter log-type to webportal config. 
* `log-type`: String. The type of job logs, could be yarn or log-manager. The default value is yarn. Current supported values are "yarn" and "log-manager".

In services-configuration.yaml, webportal section should like:
```
webportal:
    server-port: 9286
    log-type: yarn
    uri: "http://master_ip:9286"
```
