### ISSUE TITLE
pure k8s pending issues

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/pai#3545]
- [ ] error spec restAPI change:
API: /rest-server/api/v1/jobs/userName~jobName
Fields need to add for pure-k8s: 
```json
    "appExitSpec": {
      "code": 198,
      "phrase": "CONTAINER_OOD_KILLED_BY_DISKCLEANER",
      "issuer": "PAI_RUNTIME",
      "causer": "USER_CONTAINER",
      "type": "USER_FAILURE",
      "stage": "RUNNING",
      "behavior": "NON_TRANSIENT",
      "reaction": "NEVER_RETRY",
      "reason": "Container is killed by disk cleaner due to it used major disk space and all containers disk usage on the node exceeded platform limit",
      "repro": ["User program uses almost all disk space of the node"],
      "solution": [
        "Decrease per task disk space usage by such as increasing task number"
      ]
    },
    "appExitDiagnostics": "[2019-09-02 06:19:04.748]Exception from container-launch: \nExitCodeException exitCode=198: \n\tat org.apache.hadoop.util.Shell.runCommand(Shell.java:998)\n\tat org.apache.hadoop.util.Shell.run(Shell.java:884)\n\tat [2019-09-02 06:19:04.748]\n[2019-09-02 06:19:04.749]Container exited with a non-zero exit code 198. Last 40960 bytes of runtime.pai.agg.error :\n[PAI_RUNTIME_ERROR_START]\nexitcode: 198\ntrigger: diskCleanerErrorLog\nreason: |\n  container_e09_1567151775826_0020_01_000002 killed due to disk pressure. Disk size: 335G, Used: 307G(97%), Cleaner threshold: 90%, Container cost: 121GB \nsolution: |\n  Node disk is full, please try another time. If your job needs large space, please use NAS to store data.\noriginalUserExitCode: 138\ndockerStatus: \ncaughtSignal: \ncaughtException:\nmatchedUserLogString:\nerrorLogs:\n  user: |\n    \n  runtime: |\n    \n    WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.\n    1567405144 INFO USER_EXIT_CODE 138\n  diskCleaner: |\n    1567405144 ERROR ACTION \"KILL\"\n    1567405144 ERROR REASON \"container_e09_1567151775826_0020_01_000002 killed due to disk pressure. Disk size: 335G, Used: 307G(97%), Cleaner threshold: 90%, Container cost: 121GB \"\n    1567405144 ERROR SOLUTION \"Node disk is full, please try another time. If your job needs large space, please use NAS to store data.\"\n[PAI_RUNTIME_ERROR_END]\n\n[2019-09-02 06:19:04.749]",
    "appExitMessages": {
      "container": "",
      "runtime": {
        "exitcode": 198,
        "trigger": "diskCleanerErrorLog",
        "reason": "container_e09_1567151775826_0020_01_000002 killed due to disk pressure. Disk size: 335G, Used: 307G(97%), Cleaner threshold: 90%, Container cost: 121GB \n",
        "solution": "Node disk is full, please try another time. If your job needs large space, please use NAS to store data.\n",
        "originalUserExitCode": 138,
        "dockerStatus": null,
        "caughtSignal": null,
        "caughtException": null,
        "matchedUserLogString": null,
        "errorLogs": {
          "user": "",
          "runtime": "\nWARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.\n1567405144 INFO USER_EXIT_CODE 138\n",
          "diskCleaner": "1567405144 ERROR ACTION \"KILL\"\n1567405144 ERROR REASON \"container_e09_1567151775826_0020_01_000002 killed due to disk pressure. Disk size: 335G, Used: 307G(97%), Cleaner threshold: 90%, Container cost: 121GB \"\n1567405144 ERROR SOLUTION \"Node disk is full, please try another time. If your job needs large space, please use NAS to store data.\"\n"
        }
      },
      "launcher": null
    },
    "appExitTriggerMessage": "FailedTaskCount 1 has reached MinFailedTaskCount 1 in TaskRole [taskrole]",
    "appExitTriggerTaskRoleName": "taskrole",
    "appExitTriggerTaskIndex": 0,
    "appExitType": "NON_TRANSIENT",
    "virtualCluster": "default"
  },
```

 - [ ] add new exporter for k8s to get GPU usage. Free nodes, allocated nodes and so on

**Comment by Binyang2014** [comment]
Home page show correctly after updating the scheduler config `hivedscheduler.yaml`:
```yaml
kubeApiServerAddress: http://xxx.xxx.xxx.xxx:8080

physicalCluster:
  gpuTypes:
    K80:
      gpu: 1
      cpu: 4
      memory: 8192Mi
  
  cellTypes:
    K80-2GPU:
      childCellType: K80
      childCellNumber: 2
    K80-NODE:
      childCellType: K80-2GPU
      childCellNumber: 2
      isNodeLevel: true
    2-K80-NODE:
      childCellType: K80-NODE
      childCellNumber: 2
    3-K80-NODE:
      childCellType: K80-NODE
      childCellNumber: 3

  physicalCells:
  - cellType: 3-K80-NODE
    cellChildren:
    - cellAddress: xxx.xxx.xxx.xxx
    - cellAddress: xxx.xxx.xxx.xxx
      reservationId: VC2-K80
    - cellAddress: 10.151.41.26
  - cellType: 2-K80-NODE
    cellChildren:
    - cellAddress: xxx.xxx.xxx.xxx
    - cellAddress: xxx.xxx.xxx.xxx

virtualClusters:
  VC1:
    virtualCells:
    - cellType: 3-K80-NODE.K80-NODE
      cellNumber: 1
  VC2:
    virtualCells:
    - cellType: 3-K80-NODE.K80-NODE
      cellNumber: 1
    reservedCells:
    - reservationId: VC2-K80
  default:
    virtualCells:
    - cellType: 2-K80-NODE
      cellNumber: 1
```
