### ISSUE TITLE
[ERROR] CPU node always check GPU info

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#3661]
PAI version: v0.14.0

I have a cpu node, and add it to cluster. But the job-exporter report a gpu error:
`ERROR:  gpu_collector - nvidia.py:189 - exec nvidia-smi error`
This cpu node conifg of resouce as follows:
```
node-cpu:
  mem: 32G
  cpu:
     vcore: 8
  os: ubuntu16.04
```

It's confused that why this cpu node always checks gpu info?
