### ISSUE TITLE
P2 Candidate - Docker Auth information disappear in clone job

### ISSUE THREAD

**Issue by yiyione** [microsoft/pai#3829]
I have a job with docker image auth information.

```
prerequisites:
  - type: dockerimage
    auth:
      username: xxxx
      password: <% $secrets.docker_password_0 %>
      registryuri: xxxx.azurecr.io
    uri: 'xxxx.azurecr.io/grammar-transformer-base:xxxx'
    name: docker_image_0
...
```

It will disappear after clone:

```
prerequisites:
  - type: dockerimage
    uri: 'xxxx.azurecr.io/grammar-transformer-base:xxxx'
    name: docker_image_0
```

OpenPAI version: `v0.15.0`
