### ISSUE TITLE
Can not submit job after cluster servers reboot

### ISSUE THREAD

**Issue by s2100** [microsoft/pai#3946]
Hi, 

My OpanPAI version is `v0.14.0` and it works. And I need to shutdown my all server of the cluster due for maintaining. After I boot them all, I can not submit a job cause of `waiting` status for almost 2 hours and it keeps waiting.

Thanks!

**Comment by abuccts** [comment]
could you provide logs on yarn tracking page?

**Comment by s2100** [comment]
@abuccts ,

When click `Go to Application Tracking Page
` on the page of job, it jump to new page with url of `/yarn/iZbp1illiteltgz7xb9daeZ:8088/proxy/application_1575855188058_0002/`, and it shows:

```
500 Internal Server Error
nginx/1.13.8
```

**Comment by s2100** [comment]
Also add the logs of ``:

```

**Comment by abuccts** [comment]
Did you change the node ip or hostname before reboots?
Could you also share your `layout.yaml` after password removed?

/cc @ydye seems a `/etc/hosts` misconfig, pls help to have a look

**Comment by s2100** [comment]
Hi, @abuccts, @ydye ,

**layout.yaml**

```
kubernetes:
  api-servers-url: http://10.x.x.193:8080
  dashboard-url: http://10.x.x.193:9090

machine-sku:
  master:
    mem: 8
    cpu:
      vcore: 4
    os: ubuntu16.04
  worker:
    mem: 31
    gpu:
      type: NVIDIA T4
      count: 1
    cpu:
      vcore: 8
    os: ubuntu16.04

machine-list:

    - hostname: pai-master
      hostip: 10.x.x193
      machine-type: master
      etcdid: etcdid1
      docker-data: "/var/lib/docker"
      nodename: 10.x.x.193
      k8s-role: master
      dashboard: "true"
      zkid: "1"
      pai-master: "true"

    - hostname: pai-worker
      hostip: 10.x.x.42
      machine-type: worker
      etcdid: etcdid2
      docker-data: "/var/lib/docker"
      nodename: 10.0.0.42
      k8s-role: worker
      pai-worker: "true"
```

**master /etc/hosts**

```
127.0.0.1	localhost	pai-master

::1	localhost	ip6-localhost	ip6-loopback
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
```
**worker /etc/hosts**

```
127.0.0.1	localhost	pai-worker

::1	localhost	ip6-localhost	ip6-loopback
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
```
