### ISSUE TITLE
How to set environment variables or pass structure data when submitting job?

### ISSUE THREAD

**Issue by s2100** [microsoft/pai#3956]
**Organization Name**: Private Test
**Short summary about the issue/question**: 
How to set environment variables or pass structure data when submitting job?

I used to use `jobEnv` to set structure like:

```
  "jobEnvs": {
    "TASK_NAME": "the_task",
    "USER_NAME": "someone",
    "JOB_TYPE": [
      "train",
      "test"
    ],
    "trainSets": [
      "xxx", "yyy"
    ],
    "extra_config": {
      "ROOT_DIR": "/opt/outputs",
      "TRAIN": {
        "MAX_ITER": 1
      }
    }
  }
```

But I can not find any doc or code to submit with jobEnv in v0.14.0.

**OpenPAI Environment**:
- OpenPAI version: v0.14.0

Thanks!

**Comment by abuccts** [comment]
if you want to use v2 api, pls refer to [`parameters` in protocol spec](https://github.com/microsoft/pai/blob/v0.14.0/docs/pai-job-protocol.yaml#L26-L30)

**Comment by s2100** [comment]
@abuccts  It seems that `parameters` can be accessed YAML value when submitting job. But the trouble I met is that I wanna access the value inside the `running` job or container.

**Comment by abuccts** [comment]
You can either add arguments for your code to accept those parameters,
```sh
main.py --root-dir <% $parameters.root_dir %> --max-iter <% $parameters.max_iter %>
```
or use a JSON string (e.g. `json.dumps` in py) as a parameter and export to env/write to file by yourself.
```yaml
parameters:
  env: '{"jobEnvs": {"TASK_NAME": "the_task", "USER_NAME": "someone", "JOB_TYPE": ["train", "test"], "trainSets": ["xxx", "yyy"], "extra_config": {"ROOT_DIR": "/opt/outputs", "TRAIN": {"MAX_ITER": 1}}}}'
...
commands:
- export CONFIG=<% $parameters.env %>
```
