### ISSUE TITLE
P1 Candidate - a failed runtime plugin shouldn't fail the entire runtime

### ISSUE THREAD

**Issue by fanyangCS** [microsoft/pai#4014]
Please avoid apt-get or any external resource fetching, if possible.

**Comment by Binyang2014** [comment]
How about use init container to prepare binary package for user and don't install any package in user container. (For ssh, I think we can do this by building go sserver: https://github.com/gliderlabs/ssh or other ways)  This will separate runtime plugin and user commands and avoid wired issues.

**Comment by Binyang2014** [comment]
For `runtime plugin shouldn't fail entire runtime`. Maybe we can change the runtime protocol and add failurePolicy for plugins. The failurePolicy can be ignore or fail. The default value is Fail
```yaml
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: boolean
      failurePolicy: Ignore/Fail
```
