### ISSUE TITLE
insufficient capacity in physical cluster

### ISSUE THREAD

**Issue by shiyemin** [microsoft/pai#4029]
After deploy v0.16.0, i switched to hivedscheduler. When request for 1 GPU, everything is fine. However, when request for 2 GPUs, the scheduler reported "insufficient capacity in physical cluster".

Here is my config of hivedscheduler:
```
hivedscheduler:
  config: |
    physicalCluster:
      gpuTypes:
        2080Ti:
          gpu: 1
          cpu: 8
          memory: 47000Mi
      cellTypes:
        2080CARD:
          childCellType: 2080Ti
          childCellNumber: 1
        2080-NODE:
          childCellType: 2080CARD
          childCellNumber: 8
          isNodeLevel: true
      physicalCells:
      - cellType: 2080-NODE
        cellAddress: 172.16.20.224
    virtualClusters:
      default:
        virtualCells:
        - cellType: 2080-NODE.2080CARD
          cellNumber: 4
      VC1:
        virtualCells:
        - cellType: 2080-NODE.2080CARD
          cellNumber: 4
```

Job yaml:
```
protocolVersion: 2
name: shiyemin2_8b27e360
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: pai-images/pytorch1.3-py36-cu10.1
    name: docker_image_0
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: -1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 2
      cpu: 8
      memoryMB: 16384
      ports:
        tensorBoardPort_zbtnfdm1: 1
    commands:
      - '`#TEAMWISE_STORAGE_START`'
      - '`#Auto generated code, please do not modify`'
      - apt-get update
      - umask 000
      - mkdir --parents /tmp_XXXX_root/
      - apt-get install --assume-yes nfs-common
      - 'mount -t nfs4 xxx.xxx.xxx.xxx:/users/ /tmp_XXXX_root/'
      - mkdir --parents /mnt/users
      - 'mkdir --parents /tmp_XXXX_root/${PAI_USER_NAME}'
      - umount -l /tmp_XXXX_root/
      - rm -r /tmp_XXXX_root/
      - 'mount -t nfs4 xxx.xxx.xxx.xxx:/users/${PAI_USER_NAME} /mnt/users'
      - mkdir --parents /tmp_XXXX_root/
      - apt-get install --assume-yes nfs-common
      - 'mount -t nfs4 xxx.xxx.xxx.xxx:/data/ /tmp_XXXX_root/'
      - mkdir --parents /mnt/data
      - mkdir --parents /tmp_XXXX_root/share
      - umount -l /tmp_XXXX_root/
      - rm -r /tmp_XXXX_root/
      - 'mount -t nfs4 xxx.xxx.xxx.xxx:/data/share /mnt/data'
      - '`#TEAMWISE_STORAGE_END`'
      - '`#TENSORBOARD_START`'
      - '`#Auto generated code, please do not modify`'
      - >-
        (tensorboard --logdir=default:/mnt/tensorboard
        --port=$PAI_CONTAINER_HOST_tensorBoardPort_zbtnfdm1_PORT_LIST &)
      - '`#TENSORBOARD_END`'
      - echo "Test"
      - sleep 36000
      - echo "End"
defaults:
  virtualCluster: default
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
        userssh:
          type: custom
          value: >-
            ssh-rsa
            AAAAB3NzaC1yc2EAAAADAQABAAAAgQCF8YcqcFFiMin8/uOC48YObgtrNCiDx0n8GwJ1snL3aMFtGaDcxsAD+agYilRmX8vS5GmFhLg+fOjaYkeQ7RVqhHOy6qGELx9/H/bsQEMUBLQUZHJeUGB88c8M/ymI4eu0ClkfuUe+v/fRT9Bsxb6SRqK6mjqkgYf1Ri+PO0BF+Q==
            pai-job-ssh
  tensorBoard:
    randomStr: zbtnfdm1
    logDirectories:
      default: /mnt/tensorboard
  pai.storage:
    - xxxx
```

The log of hivedscheduler is:
```
I1217 11:08:23.698684       9 scheduler.go:478] [8abf95af-20bd-11ea-b2f6-50af732fad6c(default/edm6jyb5dnmpwckyedm6jyb5dnmpwcjz71h34dv56cv30-taskrole-0)]: filterRoutine: Started
I1217 11:08:23.698710       9 hived_algorithm.go:105] [8abf95af-20bd-11ea-b2f6-50af732fad6c(default/edm6jyb5dnmpwckyedm6jyb5dnmpwcjz71h34dv56cv30-taskrole-0)]: Scheduling pod...
I1217 11:08:23.698865       9 hived_algorithm.go:118] [8abf95af-20bd-11ea-b2f6-50af732fad6c(default/edm6jyb5dnmpwckyedm6jyb5dnmpwcjz71h34dv56cv30-taskrole-0)]: Scheduling new affinity group shiyemin2~shiyemin2_8b27e360/default
I1217 11:08:23.698898       9 intra_vc_scheduler.go:98] Insufficient quota in VC default for scheduling request: chain 2080-NODE, GPU numbers map[2:1], priority 10
I1217 11:08:23.698923       9 hived_algorithm.go:382] Failed to schedule group shiyemin2~shiyemin2_8b27e360/default
I1217 11:08:23.749024       9 scheduler.go:568] [8abf95af-20bd-11ea-b2f6-50af732fad6c(default/edm6jyb5dnmpwckyedm6jyb5dnmpwcjz71h34dv56cv30-taskrole-0)]: filterRoutine: Pod is waiting for preemptible or free resource to appear: insufficient capacity in physical cluster
I1217 11:08:23.749046       9 utils.go:327] [8abf95af-20bd-11ea-b2f6-50af732fad6c(default/edm6jyb5dnmpwckyedm6jyb5dnmpwcjz71h34dv56cv30-taskrole-0)]: filterRoutine: Succeeded
```

**How to reproduce it**: After deploy PAI and config hivedscheduler, submit a job requesting for 2 GPUs.

**OpenPAI Environment**: 
- OpenPAI version: v0.16.0
- OS (e.g. from /etc/os-release): ubuntu16.04
- Hardware (e.g. core number, memory size, storage size, GPU type etc.): 8x2080Ti

**Comment by shiyemin** [comment]
After some tests, i was able to submit job with multiple GPUS. For other people's convenience, i paste my configuration here:
```
hivedscheduler:
  config: |
    physicalCluster:
      gpuTypes:
        2080Ti:
          gpu: 1
          cpu: 8
          memory: 47000Mi
      cellTypes:
        2080CARD:
          childCellType: 2080Ti
          childCellNumber: 1
        2080-NODE:
          childCellType: 2080CARD
          childCellNumber: 4
          isNodeLevel: true
        1AX2080-NODE:
          childCellType: 2080-NODE
          childCellNumber: 1
      physicalCells:
      - cellType: 1AX2080-NODE
        cellChildren:
        - cellAddress: 172.16.20.224
          cellChildren:
          - cellAddress: 0
          - cellAddress: 1
          - cellAddress: 2
          - cellAddress: 3
        - cellAddress: 172.16.20.224
          cellChildren:
          - cellAddress: 4
          - cellAddress: 5
          - cellAddress: 6
          - cellAddress: 7
    virtualClusters:
      default:
        virtualCells:
        - cellType: 1AX2080-NODE.2080-NODE
          cellNumber: 1
      VC1:
        virtualCells:
        - cellType: 1AX2080-NODE.2080-NODE
          cellNumber: 1
```

Conclusion: It turns out that virtual clusters must use NODE as its cell so that scheduler can schedule at the node level.
