### ISSUE TITLE
Parameters are not simply substitution

### ISSUE THREAD

**Issue by ultmaster** [microsoft/pai#4139]
I can't do this:

```
parameters:
  task_count: 10
taskRoles:
  taskrole:
    instances: <% $parameters.task_count %>
```

The error message is

```
openpaisdk.utils.RestSrvError: (400, {'code': 'InvalidProtocolError', 'message': '[{"keyword":"type","dataPath":".taskRoles[\'taskrole\'].instances","schemaPath":"#/properties/taskRoles/patternProperties/%5E%5Ba-zA-Z_%5D%5Ba-zA-Z0-9_%5D*%24/properties/instances/type","params":{"type":"integer"},"message":"should be integer"}]'})
```

The doc explains parameters as follows:

> You can define your parameters in the Parameters section and reference them by using `<% $parameters.paramKey %>` in your commands.

I used to believe this is a simple substitution (like macro), but it turns out I was wrong. I didn't find related docs to parameters. So I'm looking for some hint on how parameters work. Thanks.

**Comment by abuccts** [comment]
The scope of `$parameters` is all task roles' **commands**, as you pasted the reference.
So you can only use the `<% $parameters.key.subkey %>` format in **commands**.

---

If you want to use something like macro in config, you can use YAML features, like [anchors](https://yaml.org/spec/1.2/spec.html#id2785586).
For your case, e.g.:
```yaml
parameters:
  task_count: &count 10
taskRoles:
  taskrole1:
    instances: *count
    commands: echo <% $parameters.task_count %>
  taskrole2:
    instances: *count
```
it's global and node level reference, but cannot be substituted inline (like in `commands` in above case).
