### ISSUE TITLE
v0.17.0 abnormal command line break 

### ISSUE THREAD

**Issue by shuangjiexu** [microsoft/pai#4306]
**v0.17.0 abnormal command line break**:

I upgrade openpai from v0.15.0 to 0.17.0 and resubmit a task from previous version.
It seems that the commands in the new version do not break line.

Here is an example:
My config file is :
```
protocolVersion: 2
name: just-test_3f34372a
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: openpai/tensorflow-py36-cu90
    name: docker_image_0
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: -1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 1
      cpu: 4
      memoryMB: 8192
    commands:
      - pip install hdfs
      - touch ~/.hdfscli.cfg
      - 'echo ''[dev.alias]'' >> ~/.hdfscli.cfg'
      - 'echo ''url = http://10.3.1.12:50070'' >> ~/.hdfscli.cfg'
      - mkdir /data
      - hdfscli download --alias=dev -t 20 /datasets/kitti_odometry.tar.gz /data
      - nvidia-smi
defaults:
  virtualCluster: default
```

and I get error of 
```
errorLogs:
  user: |
    
    Usage:
    pip install [options] <requirement specifier> [package-index-options] ...
    pip install [options] -r <requirements file> [package-index-options] ...
    pip install [options] [-e] <vcs project url> ...
    pip install [options] [-e] <local project path> ...
    pip install [options] <archive url/path> ...
    
    no such option: --alias
```

**OpenPAI Environment**:
- OpenPAI version: v0.17.0
- OS: Ubuntu 16.04.6 LTS
- Kernel: Linux ubuntu 4.4.0-142-generic
- Hardware: 
`machine-sku:
  GENERIC:
    mem: 250
    gpu:
      type: 2080ti
      count: 8
    cpu:
      vcore: 64
    os: ubuntu16.04`
