### ISSUE TITLE
Wrong VC CPU/memory constraint is applied

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4349]
My hivedscheduler config is:

```yaml
hivedscheduler:                                                                          
  config: |                                                                              
    physicalCluster:                                                                     
      gpuTypes:                                                                          
        DT:                                                                              
          gpu: 1                                                                         
          cpu: 5                                                                         
          memory: 56334Mi                                                                
        FAKE: 
          gpu: 1                                                                         
          cpu: 1                                                                         
          memory: 6826Mi                                               
      cellTypes:                                                                         
        DT-NODE:                                                                         
          childCellType: DT                                                              
          childCellNumber: 4                                                             
          isNodeLevel: true                                                              
        DT-NODE-POOL:                                                                    
          childCellType: DT-NODE                                                         
          childCellNumber: 2                                                             
        FAKE-NODE:                                                                       
          childCellType: FAKE                                                            
          childCellNumber: 5                                                             
          isNodeLevel: true                                                              
        FAKE-NODE-POOL:                                                                  
          childCellType: FAKE-NODE                                                       
          childCellNumber: 1                                                             
      physicalCells:                                                                     
      - cellType: DT-NODE-POOL                                                           
        cellChildren:                                                                    
        - cellAddress: g2                                                                
        - cellAddress: g3                                                                
      - cellType: FAKE-NODE-POOL                                                         
        cellChildren:                                                                    
        - cellAddress: n36                                                               
    virtualClusters:                                                                     
      default:                                                                           
        virtualCells:                                                                    
        - cellType: DT-NODE-POOL.DT-NODE                                                 
          cellNumber: 2                                                                  
      cpu:                                                                               
        virtualCells:                                                                    
        - cellType: FAKE-NODE-POOL.FAKE-NODE                                             
          cellNumber: 1                                                                  
```

Briefly speaking, there are 2 separate VCs:

  - the `default` vc: Users can use 56334MB memory and 5 CPUs along with 1 GPU.
  - the `cpu` vc: Users can use 6826MB memory and 1 CPU along with 1 GPU.

However, when I submit a job to `default` VC, it always reminds me about the 6826MB/1CPU limit, which is the limit of `cpu` VC. 

![image](https://user-images.githubusercontent.com/7499023/78094159-73399200-7406-11ea-9ad5-aa9af9a25c67.png)
