### ISSUE TITLE
Some jobs API response not match schema in swagger

### ISSUE THREAD

**Issue by yiyione** [microsoft/pai#4424]
During the test, I found some jobs response not match the schema in [swagger](https://github.com/microsoft/pai/blob/pai-0.18.y/src/rest-server/docs/swagger.yaml)

1. get /api/v2/jobs

schema in swagger:
```yaml
retryDelayTime:
  type: integer
  description: retry delay time
```
got response:
```json
"jobStatus": {
  ...
  "retryDelayTime": null,
```
error message:
```js
{
    keyword: 'type',
    dataPath: '[0].retryDelayTime',
    schemaPath: '#/items/properties/retryDelayTime/type',
    params: { type: 'integer' },
    message: 'should be integer'
}
// Got "retryDelayTime": null.
```

2. get /api/v2/jobs/{user}~{job}

schema in swagger:
```yaml
retryDelayTime:
  type: integer
  description: retry delay time
```
got response:
```json
"jobStatus": {
  ...
  "retryDelayTime": null,
```
error message:
```js
{
    keyword: 'type',
    dataPath: '.jobStatus.retryDelayTime',
    schemaPath: '#/properties/jobStatus/properties/retryDelayTime/type',
    params: { type: 'integer' },
    message: 'should be integer'
}
// Got "retryDelayTime": null.
```
