### ISSUE TITLE
Failed Job with custom image

### ISSUE THREAD

**Issue by ddebby** [microsoft/pai#4454]
**Organization Name**: shaiic

**Short summary about the issue/question**:

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

openpai version: 0.14.0

Submit a job with my own docker image from: docker pull ddebby/python-bartuer:v0.1

YML file as follows:

```yml

protocolVersion: 2
name:1587916656192_77d01e5
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'ddebby/python-bartuer:v0.1'
    name: docker_image_0
taskRoles:
  Task_role_1:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: 1
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 0
      cpu: 1
      memoryMB: 4096
      ports:
        jupyter: 1
    commands:
      - >-
        MY_PORT="PAI_PORT_LIST_${PAI_CURRENT_TASK_ROLE_NAME}_${PAI_CURRENT_TASK_ROLE_CURRENT_TASK_INDEX}_jupyter"
      - 'PORT=${!MY_PORT}'
        jupyter notebook --allow-root --no-browser --ip 0.0.0.0 --port=$PORT
    taskRetryCount: 0
defaults:
  virtualCluster: default
```

There is no stderr msg in `Stderr` and `Stdout`.

The failed msg is as follows:
```
Exit Code:
255
Exit Type:
UNKNOWN_FAILURE
Exit Reason:
Container failed but the failure cannot be recognized by PAI Runtime
Exit Solutions:
Check container log and find root cause
Wait result from next retry
```
