### ISSUE TITLE
Get Job Config API response content-type is text/yaml, but the body is a json string

### ISSUE THREAD

**Issue by yiyione** [microsoft/pai#4461]
```yaml
  '/api/v2/jobs/{user}~{job}/config':
    get:
      tags:
        - job
      summary: Get job configuration.
      description: This API always returns job config in v2 format (text/yaml). Old job config in v1 format will be converted automatically.
      operationId: getJobConfig
```

The document and the response header show that `Content-Type: text/yaml`
But the response body is a json string:
![Annotation job config](https://user-images.githubusercontent.com/17357108/80349338-aeae6b80-88a1-11ea-8459-a14943a47d3b.png)
