### ISSUE TITLE
Insufficient shared memory

### ISSUE THREAD

**Issue by ShawnNew** [microsoft/pai#4478]
When I want to submit a job that use pytorch to train, there will be an issue claim about no sufficient shared memory. 

I cannot also add `shmMB` into job config yaml. `ValidationError: child "taskRoles" fails because [child "Task_role_1" fails because [child "resourcePerInstance" fails because ["shmMB" is not allowed]]]` will be reported by validation check.
 
I am using openpai v0.15.0, any suggest about how to fix it?

**Comment by abuccts** [comment]
what's your config file

https://github.com/microsoft/pai/blob/17794fbe6a75b4fbf496e1011c6ef6d8c005c9a6/docs/pai-job-protocol.yaml#L60-L61

**Comment by qingdo** [comment]
When I added to the YAML file and closed it, this item disappear (extraContainerOptions: 
   shmMB: 4096). My version is 0.14.0.

I think there is another user met this issue. 
https://github.com/Microsoft/pai/issues/2656#issuecomment-573555422


My scripts is. 
```
protocolVersion: 2
name: xxx
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'ufoym/deepo:pytorch-py36-cu90'
    name: docker_image_0
taskRoles:
  Task_role_1:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: 1
    dockerImage: docker_image_0
    extraContainerOptions:
      shmMB: 4096
    resourcePerInstance:
      gpu: 8
      cpu: 32
      memoryMB: 65536
    commands:
      - echo 'done'
    taskRetryCount: 0
defaults:
  virtualCluster: default
```

**Comment by ShawnNew** [comment]
Hi @abuccts, 

My config file looks like this:
![image](https://user-images.githubusercontent.com/21559339/81140579-69262880-8f9c-11ea-9776-cb11f3a2082a.png)
I haven't change anything of this file.

**Comment by abuccts** [comment]
I mean, what's job config file. you said you submitted a pytorch job, what did you submit?

**Comment by ShawnNew** [comment]
The file looks like the following, it's just a simple command `df -h` to output shm.
```
protocolVersion: 2
name: 1588225242282_5df02a7e
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'dl-dev:latest'
    name: docker_image_0
taskRoles:
  Task_role_1:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: 1
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 1
      cpu: 4
      memoryMB: 8192
    commands:
      - '`#TEAMWISE_STORAGE_START`'
      - '`#Auto generated code, please do not modify`'
      - apt-get update
      - apt-get install --assume-yes nfs-common cifs-utils sshpass wget
      - umask 000
      - '`#TEAMWISE_STORAGE_END`'
      - cd /user/code/intention-prediction
      - df -h
    taskRetryCount: 0
defaults:
  virtualCluster: default
```
