### ISSUE TITLE
Cannot set up a read-only storage in OpenPAI

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4503]
How to reproduce:

1. Set up a ***ReadOnlyMany*** PV and corresponding PVC by:

```yaml
apiVersion: v1                                                    
kind: PersistentVolume                                            
metadata:                                                         
  name: pv-azureblob-classdata                                    
  labels:                                                         
     name: pv-azureblob-classdata                                 
spec:                                                             
  capacity:                                                       
    storage: 10Gi                                                 
  accessModes:                                                    
    - ReadOnlyMany                                                
  persistentVolumeReclaimPolicy: Retain                           
  flexVolume:                                                     
    driver: "azure/blobfuse"                                      
    secretRef:                                                    
      name: storage-hzyeurope                                     
    options:                                                      
      container: classdata                                        
      tmppath: /tmp/blobfuse                                      
      mountoptions: "--file-cache-timeout-in-seconds=120"         
---                                                               
apiVersion: v1                                                    
kind: PersistentVolumeClaim                                       
metadata:                                                         
  name: classdata                                                 
spec:                                                             
  accessModes:                                                    
    - ReadOnlyMany                                                
  storageClassName: ""                                            
  resources:                                                      
    requests:                                                     
      storage: 10Gi                                               
  selector:                                                       
    matchLabels:                                                  
      name: pv-azureblob-classdata                                
```

2. In webportal, we can see its access mode is RW:
![image](https://user-images.githubusercontent.com/7499023/81279166-58071580-9089-11ea-941f-2165b1195ab9.png)

3. We can write to the storage in container.

**Comment by Binyang2014** [comment]
It's seems like a k8s bug: https://github.com/kubernetes/kubernetes/issues/61758. According to this issue, a workaround is set readOnly in Pod spec. Such as:
```yaml
piVersion: v1
kind: Pod
metadata:
  name: nginx-flex-dysk-pvc
spec:
  containers:
  - name: nginx-flex-dysk
    image: nginx
    volumeMounts:
    - name: flexvol-mount
      mountPath: /data
  volumes:
  - name: flexvol-mount
    persistentVolumeClaim:
      claimName: pvc-dysk-flexvol
      readOnly: true
```
