### ISSUE TITLE
Feedback v0.17.0 and v1.0 deployment issues met

### ISSUE THREAD

**Issue by ypbustc** [microsoft/pai#4675]
openpai/postgresql-init-client:v0.17.0 and openpai/postgresql:v0.17.0 are missed,and installation cannot be completed!

**Comment by fanyangCS** [comment]
v0.17.0 is an internal release. suggest to upgrade to 1.0.1

**Comment by hzy46** [comment]
Hi @ypbustc ,  these containers are added in #4164 , which is part of the 1.0.0 release. So you cannot get them in 0.17.0.

Please make sure the code you used is in `pai-0.17.y` branch.

**Comment by ypbustc** [comment]
1.0.1我尝试部署了，太多的坑：


1)报pythton 没找到，ubuntu中 应该是python3了
2）requirement.sh 检测网络不通，原因是&nbsp;ansible_eth0 写死了 网卡设备名为eth0,现在ubuntu基本都不是这个名字了
3）gr.io不能访问，修改 为gcr.azk8s.cn requirement.sh 依然检测gr.io
4）worker node上暂时没有GPU卡，设置 resource_check： false&nbsp; 依然会检测。
等等，根本无法部署啊，只能退回0.17.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhiyuan He"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 晚上6:03
收件人:&nbsp;"microsoft/pai"<pai@noreply.github.com&gt;;
抄送:&nbsp;"甲骨文"<825223581@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/pai] Feedback v0.17.0 (#4675)





 
Hi @ypbustc ,  these containers are added in #4164 , which is part of the 1.0.0 release. So you cannot get them in 0.17.0.
 
Please make sure the code you used is in pai-0.17.y branch.

**Comment by ypbustc** [comment]
1.0.1我尝试部署了，太多的坑：


1)报pythton 没找到，ubuntu中 应该是python3了
2）requirement.sh 检测网络不通，原因是 ansible_eth0 写死了 网卡设备名为eth0,现在ubuntu基本都不是这个名字了
3）gr.io不能访问，修改 为gcr.azk8s.cn requirement.sh 依然检测gr.io
4）worker node上暂时没有GPU卡，设置 resource_check： false&nbsp; 依然会检测。
等等，根本无法部署啊，只能退回0.17.0







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fan yang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 下午5:57
收件人:&nbsp;"microsoft/pai"<pai@noreply.github.com&gt;;
抄送:&nbsp;"甲骨文"<825223581@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/pai] Feedback v0.17.0 (#4675)





 
v0.17.0 is an internal release. suggest to upgrade to 1.0.1

**Comment by ypbustc** [comment]
我pull的docker就是dev-box:v0.17.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhiyuan He"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 晚上6:03
收件人:&nbsp;"microsoft/pai"<pai@noreply.github.com&gt;;
抄送:&nbsp;"甲骨文"<825223581@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/pai] Feedback v0.17.0 (#4675)





 
Hi @ypbustc ,  these containers are added in #4164 , which is part of the 1.0.0 release. So you cannot get them in 0.17.0.
 
Please make sure the code you used is in pai-0.17.y branch.

**Comment by ypbustc** [comment]
1.0.1我尝试部署了，太多的坑： 1)报pythton 没找到，ubuntu中 应该是python3了 2）requirement.sh 检测网络不通，原因是&amp;nbsp;ansible_eth0 写死了 网卡设备名为eth0,现在ubuntu基本都不是这个名字了 3）gr.io不能访问，修改 为gcr.azk8s.cn requirement.sh 依然检测gr.io 4）worker node上暂时没有GPU卡，设置 resource_check： false&amp;nbsp; 依然会检测。 等等，根本无法部署啊，只能退回0.17.0


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fan yang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 下午5:57
收件人:&nbsp;"microsoft/pai"<pai@noreply.github.com&gt;;
抄送:&nbsp;"甲骨文"<825223581@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/pai] Feedback v0.17.0 (#4675)





 
v0.17.0 is an internal release. suggest to upgrade to 1.0.1

**Comment by ypbustc** [comment]
&nbsp;Now “OpenPAI Handbook”&nbsp; is also "page not found"。
https://openpai.readthedocs.io/en/release-1.0.0/manual/cluster-admin/upgrade-guide.html




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fan yang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 下午5:57
收件人:&nbsp;"microsoft/pai"<pai@noreply.github.com&gt;;
抄送:&nbsp;"甲骨文"<825223581@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/pai] Feedback v0.17.0 (#4675)





 
v0.17.0 is an internal release. suggest to upgrade to 1.0.1

**Comment by fanyangCS** [comment]
Could you tell us where you find this url? We will fix it. For now please visit https://openpai.readthedocs.io/ to start your exploration on related document (if you would like to learn information about the installation, you can start from here: https://openpai.readthedocs.io/en/latest/manual/cluster-admin/README.html ).

v1.0.1 has a new way of installation. It does *not* provide a upgrade path from previous version. Instead, it requires to clean previous deployment and install v1.0.1 from scratch.

**Comment by ypbustc** [comment]
今天又恢复正常了。 URL:&nbsp;&nbsp;https://github.com/microsoft/pai&nbsp;&nbsp;

For cluster administrators -&gt; Installation and upgrade -&gt;upgrade guide


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fan yang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 晚上9:54
收件人:&nbsp;"microsoft/pai"<pai@noreply.github.com&gt;;
抄送:&nbsp;"甲骨文"<825223581@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/pai] Feedback v0.17.0 (#4675)





 
Could you tell us where you find this url? We will fix it. For now please visit https://openpai.readthedocs.io/ to start your exploration on related document (if you would like to learn information about the installation, you can start from here: https://openpai.readthedocs.io/en/latest/manual/cluster-admin/README.html ).
 
v1.0.1 has a new way of installation. It does not provide a upgrade path from previous version. Instead, it requires to clean previous deployment and install v1.0.1 from scratch.

**Comment by hzy46** [comment]
At this period, we assume every worker node must have GPU. So you may not be able to deploy v0.17.0, too.

**Comment by hzy46** [comment]
For network issues, use the following config for v1.0.1 in China:

```yaml
user: <ssh user>
password: <ssh password>
branch_name: pai-1.0.y
docker_image_tag: v1.0.1

openpai_kube_network_plugin: weave

gcr_image_repo: "gcr.azk8s.cn"
kube_image_repo: "gcr.azk8s.cn/google-containers"
kubeadm_download_url: "https://shaiictestblob01.blob.core.chinacloudapi.cn/share-all/kubeadm"
hyperkube_download_url: "https://shaiictestblob01.blob.core.chinacloudapi.cn/share-all/hyperkube"

openpai_kubespray_extra_var:
  pod_infra_image_repo: "gcr.azk8s.cn/google_containers/pause-{{ image_arch }}"
  dnsautoscaler_image_repo: "gcr.azk8s.cn/google_containers/cluster-proportional-autoscaler-{{ image_arch }}"
  tiller_image_repo: "gcr.azk8s.cn/kubernetes-helm/tiller"
  registry_proxy_image_repo: "gcr.azk8s.cn/google_containers/kube-registry-proxy"
  metrics_server_image_repo: "gcr.azk8s.cn/google_containers/metrics-server-amd64"
  addon_resizer_image_repo: "gcr.azk8s.cn/google_containers/addon-resizer"
  dashboard_image_repo: "gcr.azk8s.cn/google_containers/kubernetes-dashboard-{{ image_arch }}"
```

Ignore all information printed by requirement check, type `continue` to finish installation.
