### ISSUE TITLE
When import a job protocol contains ports info, the submit job page will have bugs

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#4696]
Reproduce:

   import a job config from submit job page

Job config:
```
protocolVersion: 2
name: marketplace_job
type: job
jobRetryCount: 0
prerequisites:
- type: dockerimage
  uri: openpai/standard:python_3.6-pytorch_1.2.0-gpu
  name: docker_image_0
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: -1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 1
      cpu: 4
      memoryMB: 8192
      ports:
      - FLASK_PORT: 1
    commands:
    - export DATA_DIR=/mnt/confignfs/couplet/checkpoints
    - export CODE_DIR=/mnt/confignfs/couplet
    - export FLASK_PORT=$PAI_PORT_LIST_taskrole_0_FLASK_PORT
    - pip install fairseq
    - pip install flask
    - pip install gunicorn
    - cd ${CODE_DIR}
    - gunicorn --bind=0.0.0.0:${FLASK_PORT} app:app
defaults:
  virtualCluster: default
extras:
  com.microsoft.pai.runtimeplugin:
  - plugin: teamwise_storage
    parameters:
      storageConfigNames:
      - confignfs
```
