### ISSUE TITLE
Log-manager 

### ISSUE THREAD

**Issue by zlf0625** [microsoft/pai#4816]
**Organization Name**:

**Short summary about the issue/question**:
Cannot access log-manager (through the button `browser log folder`, error 502 Bad Gateway after about 1-5 minutes of page loading) and `stdout`/`stderr` (only showing "Loading..." forever). Found "log-manager-xxx" are running correctly. The logs are like `x.x.x.x - [17/Aug/2020:03:20:18 +0000] "GET /healthz HTTP/1.1" 200 18 "-" "kube-probe/1.15"`. All other functionalities seem to work correctly (job submission / running / ...).

**Brief what process you are following**:

**How to reproduce it**: not sure (but I reinstalled (after `kubeadm reset` on all machines) the OpenPAI, and this problem was still there)

**OpenPAI Environment**:
- OpenPAI version: v1.0
- Cloud provider or hardware configuration: local cluster
- OS (e.g. from /etc/os-release): PRETTY_NAME="Ubuntu 18.04.4 LTS"
- Kernel (e.g. `uname -a`): 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by Binyang2014** [comment]
Can you access `http://work_node_ip:9103/log-manager/` and `http://work_node_ip:9103/healthz/` in your browser?

**Comment by zlf0625** [comment]
Yes, if I check my master node, `http://work_node_ip:9103/log-manager/` shows an empty directory. I have never seen the link with port `9103` before. However, the link from the `Browse log folder` button is like `http://MASTER-NODE-IP/log-manager/WORKER-NODE-IP:9103/MY-USER/...` (without `:9103`). 

After your reply, I just found that workers' log-manager is not empty and that the link `http://WORKER-NODE-IP:9103/log-manager/MY-USER/...` does work (substituting `MASTER-NODE-IP` with `WORKER-NODE-IP:9103`)...

Why did this happen?

**Comment by Binyang2014** [comment]
Actually, pylon will redirect the ` http://MASTER-NODE-IP/log-manager/WORKER-NODE-IP:9103/MY-USER/...` to `http://WORKER-NODE-IP:9103/log-manager/MY-USER/...` 
https://github.com/microsoft/pai/blob/e116f7722fc549ac228bde7620e411a62a9204ce/src/pylon/deploy/pylon-config/location.conf.template#L91-L95

Please make sure the `pylon` is working

**Comment by zlf0625** [comment]
Thanks for the clarification. I saw pod `pylon-ds-....` seems to run normally.

`http://WORKER-NODE-IP:9103/log-manager/MY-USER/...` (after redirected) is working. Also, `http://MASTER-NODE:9103/healthz/` returns "Log manager ready." and `http://MASTER-NODE:9103/` shows `Welcome to OpenResty`.

Is there anything more I can check?

**Comment by fanyangCS** [comment]
@Binyang2014, is it k8s CNI issue?

**Comment by Binyang2014** [comment]
@zlf0625 Can you `docker exec` into the pylon container and run `curl http://worker_ip:9103`. You may need to install curl in pylon container first.

If this command failed, you can try to re-config the pylon daemonSet to use `hostNetwork`. You can change this in k8s-dashboard.

**Comment by zlf0625** [comment]
I tried `docker exec` into the pylon container (on the master node) and got `curl: (7) Failed to connect to XXX port 9103: Connection timed out` (worker IPs). But I can directly connect to the same worker address (with port 9103) (outside the container).

**Comment by Binyang2014** [comment]
Can you try to change the pylon-ds to use `hostNetwork`? Using `hostNetwork` may solve this issue.  And what CNI do you use? Weave or Calico. 
Please run `kuebctl get ds -n kube-system`. And make sure you can find weave or calico cni. All the weave/calico related pods should in ready status.
And please run ` kubectl get deployment -n kube-system`
Make sure you can find `coredns` services.

**Comment by zlf0625** [comment]
I paste the results here first for reference:
Running `kubectl get ds -n kube-system` gets:
```
NAME                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
calico-node                        5         5         5       5            5           <none>                        5d2h
k8s-host-device-plugin-daemonset   5         5         5       5            5           <none>                        4d
kube-proxy                         5         5         5       5            5           beta.kubernetes.io/os=linux   5d2h
nvidia-device-plugin-daemonset     5         5         5       5            5           <none>                        4d
```
Running `kubectl get deployment -n kube-system` gets:
```
calico-kube-controllers        1/1     1            1           5d2h
coredns                        1/1     1            1           4d2h
dns-autoscaler                 1/1     1            1           5d2h
kubernetes-dashboard-openpai   1/1     1            1           4d
```
I think I am using the default value (Calico), and `coredns` is running correctly.

**Comment by Binyang2014** [comment]
Can you run `kubectl edit ds pylon-ds`
Then add `hostNetwork: true` undser `sepc.template.spec`. It would be like
```yaml
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pylon
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pylon
      name: pylon
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pai-master
                operator: In
                values:
                - "true"
      containers:
      - command:
        - /bin/bash
        - /pylon-config/run.sh
```
I am not sure the reason for this problem, hope using hostNetwork could mitigate this issue
