### ISSUE TITLE
Submit job storage UI still uses old protocol extra define

### ISSUE THREAD

**Issue by debuggy** [microsoft/pai#4858]
should change old protocol definition:

```
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: teamwise_storage
      parameters:
        storageConfigNames:
          - confignfs
```
to new protocol definition:

```
extras:
  storages:
    - name: confignfs
      mountPath: /mnt/confignfs
```

and edit UI in corresponding.
