### ISSUE TITLE
Resource in job config will be changed after uploading to webportal

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4881]
1. save this config to a yaml file. It claims 2 gpu, 10 cpu, and 6500 MB mem.

```yaml
protocolVersion: 2
name: hello-world-job
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'openpai/standard:python_3.6-tensorflow_1.15.0-gpu'
    name: docker_image_0
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: -1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 2
      cpu: 10
      memoryMB: 6500
    commands:
      - 'git clone https://github.com/tensorflow/models'
      - cd models
      - git reset --hard 62bf6fc0bb2b41a4fb851909c132647a7e0774b0
      - cd research/slim
      - >-
        python download_and_convert_data.py --dataset_name=cifar10
        --dataset_dir=/tmp/data
      - >-
        python train_image_classifier.py --dataset_name=cifar10
        --dataset_dir=/tmp/data --max_number_of_steps=1000
defaults:
  virtualCluster: default
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
```

2. upload the yaml config to webportal, the resource has been changed to 

![image](https://user-images.githubusercontent.com/7499023/92428170-f682bf00-f1c0-11ea-84c5-92423d5b4726.png)
