### ISSUE TITLE
Virtual Cluster management capability

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4906]
**Organization Name**:
Advantech

**Short summary about the issue/question**:
1. Can resource percentage be adjusted between virtual clusters in OpenPAI v1.x?
2. Can multiple virtual cluster be created for 1 node virtual cluster in OpenPAI v1.x?

**Comment by fanyangCS** [comment]
1. Yes.
2. Yes.

You will need to look through our document for details.

**Comment by JosephKang** [comment]
@fanyangCS ,

Currently I only learn to set virtual cluster through the below hive scheduling by node
- https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-set-up-virtual-clusters.html#what-is-hived-scheduler-and-how-to-configure-it

Could you please help to share the document for the above 2 scenario?

Thanks

**Comment by fanyangCS** [comment]
@yqwang-ms , could you help?

**Comment by yqwang-ms** [comment]
Example conf for scenario 2:

Assume you have a node (its k8s node name is worker1), which has 4 gpus, and each gpu corresponding to 5 cpu and 50000Mi memory (for how to calculate this, check https://github.com/microsoft/hivedscheduler/blob/master/doc/user-manual.md#config-quickstart).
Then we setup 2 vcs, vc1 has 1 gpu quota, vc2 has 3 gpu quota now:
···
hivedscheduler:
  config: |
    physicalCluster:
      skuTypes:
        K80:
          gpu: 1
          cpu: 5
          memory: 50000Mi
      cellTypes:
        K80-NODE:
          childCellType: K80
          childCellNumber: 4
          isNodeLevel: true
      physicalCells:
      - cellType: K80-NODE
        cellAddress: worker1
    virtualClusters:
      vc1:
        virtualCells:
        - cellType: K80-NODE.K80
          cellNumber: 1
      vc2:
        virtualCells:
        - cellType: K80-NODE.K80
          cellNumber: 3
···

For scenario 1:
If you move 1 gpu quota from vc1 to vc2, you can update the config to:
···
hivedscheduler:
  config: |
    physicalCluster:
      skuTypes:
        K80:
          gpu: 1
          cpu: 5
          memory: 50000Mi
      cellTypes:
        K80-NODE:
          childCellType: K80
          childCellNumber: 4
          isNodeLevel: true
      physicalCells:
      - cellType: K80-NODE
        cellAddress: worker1
    virtualClusters:
      vc1:
        virtualCells:
        - cellType: K80-NODE.K80
          cellNumber: 2
      vc2:
        virtualCells:
        - cellType: K80-NODE.K80
          cellNumber: 2
···
See the "Apply Configuration in Cluster" in https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-set-up-virtual-clusters.html#what-is-hived-scheduler-and-how-to-configure-it, to make the config take effects.

**Comment by JosephKang** [comment]
Thanks for answering.
Any plan to have the configuration capability on webportal just like version 0.x?

**Comment by yqwang-ms** [comment]
This is exactly in our current planing, and design ongoing. @fanyangCS

**Comment by JosephKang** [comment]
@yqwang-ms,

I set the virtualCluster cellType down to skutypes as shown below
`
hivedscheduler:
  config: |
    physicalCluster:
      skuTypes:
        DT:
          gpu: 1
          cpu: 3
          memory: 90613Mi
      cellTypes:
        DT-NODE:
          childCellType: DT
          childCellNumber: 4
          isNodeLevel: true
        DT-NODE-POOL:
          childCellType: DT-NODE
          childCellNumber: 2
      physicalCells:
      - cellType: DT-NODE-POOL
        cellChildren:
        - cellAddress: testgpu0-1111945-iaas
        - cellAddress: testgpu1-1112050-iaas
    virtualClusters:
      devgpu:
        virtualCells:
        - cellType: DT-NODE-POOL.DT-NODE.DT
          cellNumber: 2
      devgpunew:
        virtualCells:
        - cellType: DT-NODE-POOL.DT-NODE.DT
          cellNumber: 6
`

**Comment by JosephKang** [comment]
@yqwang-ms,

I set the virtualCluster cellType down to skutypes as shown below
```
hivedscheduler:
  config: |
    physicalCluster:
      skuTypes:
        DT:
          gpu: 1
          cpu: 3
          memory: 90613Mi
      cellTypes:
        DT-NODE:
          childCellType: DT
          childCellNumber: 4
          isNodeLevel: true
        DT-NODE-POOL:
          childCellType: DT-NODE
          childCellNumber: 2
      physicalCells:
      - cellType: DT-NODE-POOL
        cellChildren:
        - cellAddress: testgpu0-1111945-iaas
        - cellAddress: testgpu1-1112050-iaas
    virtualClusters:
      devgpu:
        virtualCells:
        - cellType: DT-NODE-POOL.DT-NODE.DT
          cellNumber: 2
      devgpunew:
        virtualCells:
        - cellType: DT-NODE-POOL.DT-NODE.DT
          cellNumber: 6

```

However, the assigned task is executed only when the specified resource is 1 SKU resource. Otherwise, the task will be kept in the waiting status as shown in the snapshot below.

![2020-09-16_123023](https://user-images.githubusercontent.com/3213161/93292956-67f1eb80-f819-11ea-8c28-a22dd8a1f503.png)

May I know if I missed anything?

**Comment by yqwang-ms** [comment]
Good catch! It should be the same issue as https://github.com/microsoft/pai/issues/4029#issuecomment-566837732.
So it is by design in HiveD now, and we are trying to improve this.

To temp resolve this issue, you can adjust your config to be:
```
hivedscheduler:
  config: |
    physicalCluster:
      skuTypes:
        DT:
          gpu: 1
          cpu: 3
          memory: 90613Mi
      cellTypes:
        DT-HALF-NODE:
          childCellType: DT
          childCellNumber: 2
        DT-NODE:
          childCellType: DT-HALF-NODE
          childCellNumber: 2
          isNodeLevel: true
        DT-NODE-POOL:
          childCellType: DT-NODE
          childCellNumber: 2
      physicalCells:
      - cellType: DT-NODE-POOL
        cellChildren:
        - cellAddress: testgpu0-1111945-iaas
        - cellAddress: testgpu1-1112050-iaas
    virtualClusters:
      devgpu:
        virtualCells:
        - cellType: DT-NODE-POOL.DT-NODE.DT-HALF-NODE
          cellNumber: 1
      devgpunew:
        virtualCells:
        - cellType: DT-NODE-POOL.DT-NODE
          cellNumber: 1
        - cellType: DT-NODE-POOL.DT-NODE.DT-HALF-NODE
          cellNumber: 1
```

In this way, 1-GPU pod and 2-GPU pod can be scheduled in vc devgpu.
And 1-GPU pod, 2-GPU pod, 3-GPU pod, 4-GPU pod can be scheduled in vc devgpunew.
