### ISSUE TITLE
Task retry will cause wrong framework retry records

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4911]
How to reproduce:

1. Use this job config:

```yaml
protocolVersion: 2
name: retry_test_3_a9a85a47
type: job
jobRetryCount: 10
prerequisites:
  - type: dockerimage
    uri: 'openpai/standard:python_3.6-pytorch_1.2.0-gpu'
    name: docker_image_0
taskRoles:
  taskrole:
    instances: 2
    completion:
      minFailedInstances: 1
      minSucceededInstances: -1
    taskRetryCount: 2
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 1
      cpu: 1
      memoryMB: 2000
    commands:
      - printenv
      - exit 133
defaults:
  virtualCluster: default
extras:
  gangAllocation: false
```

2. Go to the job retry page:

![image](https://user-images.githubusercontent.com/7499023/93429958-824cc780-f8f4-11ea-8801-13dc51730845.png)

Some tasks are recorded in `RUNNING` status. It is not true.

The cause for this problem:

FC will output framework object every time a task is retried. But the fluentd only records the framework object when the first task retry happens.
