### ISSUE TITLE
Simplify CompletionPolicy for common users

### ISSUE THREAD

**Issue by yqwang-ms** [microsoft/pai#4947]
User easy to misconfig job CompletionPolicy, such as:
```
taskRoles:
  taskrole:
    instances: 1500
    completion:
      minFailedInstances: 500
      minSucceededInstances: 500
```

We may need to simplify this and guide user to set it correctly, such as:
1. We could produce a warning for this kind of jobs. minFailedInstances and minSucceededInstances are much smaller than "instances"
2. We can also provide several common policies, such as minfail = 1, minsucc = instances, etc, so most user can directly select one of them, and for advance users they can still specify these specific numbers.
