### ISSUE TITLE
Rest-server job detail API becomes slow and CPU-intensive

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#5012]
I compared the job detail API of `v1.2.1` and current master (commit id 03d83a7f8c0b8ec86306b24772f7e98784d253a6) with the same test job:
```yaml
protocolVersion: 2
name: admin_0c0cdf32
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'openpai/standard:python_3.6-pytorch_1.2.0-gpu'
    name: docker_image_0
taskRoles:
  taskrole:
    instances: 2000
    completion:
      minFailedInstances: 1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 4
      cpu: 20
      memoryMB: 225336
    commands:
      - sleep 1000s
defaults:
  virtualCluster: default
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
  hivedScheduler:
    jobPriorityClass: oppo
    taskRoles:
      taskrole:
        skuNum: 4
        skuType: DT

```

### In v1.2.1:
If we only open 1 job detail page, the api call takes about 400\~500ms.
If we open 10 job detail pages, the api call also takes about 400\~500ms. And the rest-server CPU usage is lower than 10%.

### In master branch:
If we only open 1 job detail page, the api call takes about 3\~3.5s.
If we open 10 job detail pages, the api call also takes over 30s. And the rest-server CPU usage is 100%.
It also slows down other requests (see the following pic: the call to `ssh` is also slow):
![image](https://user-images.githubusercontent.com/7499023/97153780-032d9780-17ae-11eb-9816-7b9e30f254b3.png)
