### ISSUE TITLE
CPU task scheduling limitation

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#5044]
**Organization Name**:
Advantech

**Short summary about the issue/question**:
CPU task scheduling resource is limited

**Brief what process you are following**:
We only have one GPU worker and hope to utilize the cpu resource. Therefore I create 2 VCs, one is GPU VC and the other is CPU VC, within the GPU node:
**CPU:** 48 Core
**GPU:** 4 Core
**RAM:** 256GB

The scheduler configuration is listed below
```
hivedscheduler:
  config: |
    physicalCluster:
      skuTypes:
        DT:
          gpu: 1
          cpu: 5
          memory: 31000Mi
        CPU:
          cpu: 1
          memory: 5000Mi
      cellTypes:
        DT-NODE:
          childCellType: DT
          childCellNumber: 4
          isNodeLevel: true
        DT-NODE-POOL:
          childCellType: DT-NODE
          childCellNumber: 1
        CPU-NODE:
          childCellType: CPU
          childCellNumber: 24
          isNodeLevel: true
        CPU-NODE-POOL:
          childCellType: CPU-NODE
          childCellNumber: 1
      physicalCells:
      - cellType: DT-NODE-POOL
        cellChildren:
        - cellAddress: ainode
      - cellType: CPU-NODE-POOL
        cellChildren:
        - cellAddress: ainode
    virtualClusters:
      prodgpu:
        virtualCells:
        - cellType: DT-NODE-POOL.DT-NODE
          cellNumber: 1
      prodcpu:
        virtualCells:
        - cellType: CPU-NODE-POOL.CPU-NODE
          cellNumber: 1

```

The GPU task submission is OK, but the CPU task submission will be failed if the total number of used CPU in existing running CPU tasks is larger than 4. The scheduler error and task exit error messages are listed below

**The error message in hivedscheduler-ds-prodcpu-0 pod log**
```
I1102 08:13:57.193450       6 scheduling_queue.go:908] About to try and schedule pod default/b328cf2cdf017d756c695ab4554a9333-jupyter-0
I1102 08:13:57.193487       6 scheduler.go:453] Attempting to schedule pod: default/b328cf2cdf017d756c695ab4554a9333-jupyter-0
E1102 08:13:57.197399       6 factory.go:660] Error scheduling default/b328cf2cdf017d756c695ab4554a9333-jupyter-0: Code: 400, Message: hivedscheduler: User Error: [f702d08a-ff9b-4246-b384-e9a2aa83a5a5(default/b328cf2cdf017d756c695ab4554a9333-jupyter-0)]: filterRoutine: Failed: Pod does not exist, completed or has not been informed to the scheduler; retrying
I1102 08:13:57.197458       6 factory.go:742] Updating pod condition for default/b328cf2cdf017d756c695ab4554a9333-jupyter-0 to (PodScheduled==False, Reason=Unschedulable)
E1102 08:13:57.266701       6 scheduler.go:481] error selecting node for pod: Code: 400, Message: hivedscheduler: User Error: [f702d08a-ff9b-4246-b384-e9a2aa83a5a5(default/b328cf2cdf017d756c695ab4554a9333-jupyter-0)]: filterRoutine: Failed: Pod does not exist, completed or has not been informed to the scheduler
```
**The task exit error message**
```
Exit Code:
-1204
Exit Type:
UNKNOWN_FAILURE
Exit Reason:
Failed to start docker container due to unknown error
Pod failed: PodPattern matched: containers: - name: app reason: ContainerCannotRun message: >- OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: device error: 4: unknown device\\\\n\\\"\"": unknown code: 128
Exit Solutions:
Check diagnostics and find root cause
Wait result from next retry
Contact Cluster Admin
```

**How to reproduce it**:
Keep a CPU task with 4 CPU and then assign a CPU task with random number of CPU resource.

**OpenPAI Environment**:
- OpenPAI version:
v1.0.1
- Cloud provider or hardware configuration:
Physical Node
- OS (e.g. from /etc/os-release):
 Ubuntu 16.04.7 LTS
- Kernel (e.g. `uname -a`):
4.4.0-186
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
CPU: 48 Core
GPU: 4 Core
RAM: 256GB

**Comment by JosephKang** [comment]
It might need to adjust prodcpu hivescheduler setting based on current behavior.

**Comment by abuccts** [comment]
Hi, hived scheduler doesn't support mixed gpu and cpu types on one node by design. For gpu nodes, `nvidia-container-runtime` needs to be installed and configured as default Docker runtime, while for cpu nodes, it must not be the default Docker runtime.

If you really need gpu jobs and cpu only jobs on one single node, then using default scheduler instead of hived might be a better choice.

**Comment by JosephKang** [comment]
@abuccts ,

How to set default scheduler in services-configuration.yaml?

Thanks

**Comment by abuccts** [comment]
hived scheduler schedules "cell" without knowing it is gpu or cpu task, and sets the scheduling result (cell indices) in env `NVIDIA_VISIBLE_DEVICES`. If the node doesn't have nvidia runtime, the env will be ignored and the container will be a cpu container. So if you configure less cpu cell (not greater than gpu cell) on one node it may work, but the cpu containers will still have access to specific gpus.

---

To set default scheduler, just change config to empty:
```yaml
hivedscheduler:
  config: |
```
then restart corresponding services:
```sh
python paictl.py service stop -n hivedscheduler rest-server webportal
python paictl.py config push -p /config/path -m service
python paictl.py service start -n hivedscheduler rest-server webportal
```

**Comment by JosephKang** [comment]
Thanks @abuccts ,

The empty hivescheduler setting might be the best solution for the 1 GPU work situation. 

In addition, I try to change the default vc name with empty hivescheduler setting by changing groupname and virtualClusters and it doesn't work. May I know how to change the default vc name in this situation?  

```
authentication:
  OIDC: false

  group-manager:
    group-data-source: basic

    # Admin group name and its user list
    admin-group:
      groupname: admingroup
      description: "admin's group"
      externalName: ""
      extension:
        acls:
          virtualClusters: []
          admin: true

    default-group:
      groupname: default
      description: "group for default vc"
      externalName: ""
      extension:
        acls:
          virtualClusters: ["default"]
          admin: false
```
