### ISSUE TITLE
CPU only cluster deployment

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#5084]
**Organization Name**:
Advantech

**Short summary about the issue/question**:
CPU only cluster deployment

**Brief what process you are following**:
Hope to deploy CPU only cluster but it is not support in current released script.

**How to reproduce it**:
NA

**OpenPAI Environment**:
- OpenPAI version:
v1.0.1.
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
No GPU

**Anything else we need to know**:

**Comment by JosephKang** [comment]
I try several unofficial approach but still failed
1. Setup master at first and plan to add CPU workers later. Failed due to configuration generation script don't support
2. Installation the master and cpu worker after removing gpu checking script. https://github.com/microsoft/pai/blob/master/contrib/kubespray/script/service-boot.sh#L49-L64. The approach is failed anyway.

**Comment by hzy46** [comment]
Here's my suggestion to install CPU-only cluster from scratch in current release.

0. I highly recommend you to use v1.3.0, instead of v1.0.1 to install the CPU-only cluster. The support for CPU-only cluster is not fully completed in version 1.0.x.

1. Use `quick-start-kubespray.sh` to start K8S. But don't use `quick-start-service.sh` to start PAI service.

2. Start a dev box container manually by following https://openpai.readthedocs.io/en/latest/manual/cluster-admin/basic-management-operations.html#pai-service-management-and-paictl

   In the dev-box container, confirm kubectl works (you can use command `kubectl get node -o wide`).

3. In the container-box, create a `config folder`, and create two files, `services-configuration.yaml` and `layout.yaml`, in this folder.

    These two files are used as the config in openpai. I will not go throgh it entirely. For a default setting, you can refer to the following:

`layout.yaml`:

```yaml
# kubernetes api server and dashboard
kubernetes:
  api-servers-url: https://10.0.0.32:6443
  dashboard-url: https://10.0.0.32:9090

# TODO please modify it according to your own hardware
machine-sku:
  GENERIC-MASTER:
    mem: 1
    gpu:
      type: generic
      count: 1
    cpu:
      vcore: 1
    os: ubuntu16.04

  GENERIC-WORKER:
    mem: 1
    gpu:
      type: generic
      count: 1
    cpu:
      vcore: 1
    os: ubuntu16.04

machine-list:
    - hostname: g1
      nodename: g1
      hostip: 10.0.0.32
      machine-type: GENERIC-MASTER
      dashboard: "true"
      pai-master: "true"
    - hostname: g2
      nodename: g2
      hostip: 10.0.0.33
      machine-type: GENERIC-WORKER
      pai-worker: "true"
    - hostname: g3
      nodename: g3
      hostip: 10.0.0.34
      machine-type: GENERIC-WORKER
      pai-worker: "true"
```

`services-configuration.yaml`:

```yaml
cluster:
  common:
    cluster-id: pai
    cluster-type: k8s
    k8s-rbac: "true"
    job-history: "true"
    data-path: "/datastorage"
    qos-switch: " | default('false') "
    docker-data-root: "/mnt/docker"

  # the docker registry to store docker images that contain system services like frameworklauncher, hadoop, etc.
  docker-registry:

    # The namespace in your registry. If the registry is docker.io, the namespace will be your user account.
    namespace: openpai

    # E.g., gcr.io.
    # if the registry is hub.docker, please fill this value with docker.io
    domain: docker.io
    # If the docker registry doesn't require authentication, please comment username and password
    
    #username: <username>
    
    
    #password: <password>
    

    tag: v1.3.0

    # The name of the secret in kubernetes will be created in your cluster
    # Must be lower case, e.g., regsecret.
    secret-name: pai-secret


rest-server:
#  # launcher type. k8s or yarn
#  launcher-type: k8s
  # database admin username
  default-pai-admin-username: admin
  # database admin password
  default-pai-admin-password: admin-password


webportal:
  server-port: 9286

#If you want to customize the scheduling config, such add more virtual clusters or more gpu types, check:
#https://github.com/microsoft/pai/blob/master/docs/hivedscheduler/devops.md
hivedscheduler:
  config: |
    physicalCluster:
      skuTypes:
        CPU:
          gpu: 0
          cpu: 5
          memory: 5000Mi
      cellTypes:
        CPU-NODE:
          childCellType: CPU
          childCellNumber: 4
          isNodeLevel: true
        CPU-NODE-POOL:
          childCellType: CPU-NODE
          childCellNumber: 2
      physicalCells:
      - cellType: CPU-NODE-POOL
        cellChildren:
        - cellAddress: g3
        - cellAddress: g2
    virtualClusters:
      default:
        virtualCells:
        - cellType: CPU-NODE-POOL.CPU-NODE
          cellNumber: 2


# uncomment following section, if you want to customize the authentication solution.
authentication:
  OIDC: false

  # If OIDC is set as the value true, you will have to configure the following properties.
  #OIDC-type: AAD
  #
  #AAD:
  #  # If you wanna configure AAD-OIDC for OpenPAI, the following configuration is mandatory.
  #  # National Clouds endpoint list https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud
  #  # AZURE: https://login.microsoftonline.com/{tenantID}/v2.0/.well-known/openid-configuration
  #  # China: https://login.partner.microsoftonline.cn/{tenantID}/v2.0/.well-known/openid-configuration
  #  # Germany: https://login.microsoftonline.de/{tenantID}/v2.0/.well-known/openid-configuration
  #  wellKnownURL: https://login.microsoftonline.com/{tenantID}/v2.0/.well-known/openid-configuration
  #
  #  # Required
  #  tenantID: ${tenat_id}
  #
  #  # Required, the client ID of your app in AAD
  #  clientID: ${your_client_id}
  #
  #  # Required if `responseType` is 'code', 'id_token code' or 'code id_token'.
  #  # If app key contains '\', replace it with '\\'.
  #  clientSecret: '${your_client_secret}'
  #
  #  # Optional. The lifetime of nonce in session or cookie, the default value is 3600 (seconds).
  #  nonceLifetime: null
  #
  #  # Optional. The max amount of nonce saved in session or cookie, the default value is 10.
  #  nonceMaxAmount: 5
  #
  #  # Optional. The clock skew allowed in token validation, the default value is 300 seconds.
  #  clockSkew: null
  #
  #  # Optional.
  #  # If you want to get access_token for a specific resource, you can provide the resource here; otherwise,
  #  # set the value to null.
  #  # Note that in order to get access_token, the responseType must be 'code', 'code id_token' or 'id_token code'.
  #  resourceURL: 'https://graph.windows.net'

  group-manager:
    # basic: If you set group-data-source as the value basic, admin should manually modify user's grouplist.
    # winbind: If you set group-data-source as the value winbind, the user's grouplist will get from winbind server based on your configuration.
    group-data-source: basic

    # If you set winbind as your data source, you should configure this configuration.
    # winbind-server-address: xxxxxxx

    # Admin group name and its user list
    admin-group:
      groupname: admingroup
      description: "admin's group"
      externalName: ""
      extension:
        acls:
          virtualClusters: []
          admin: true

    # Group for default vc.
    # For yarn default queue hack.
    default-group:
      groupname: default
      description: "group for default vc"
      externalName: ""
      extension:
        acls:
          virtualClusters: ["default"]
          admin: false

  #  # If the following groups are not in the data store, it will be created by default.
  #  grouplist:
  #    - groupname: forexample
  #      # internal name
  #      description: forexample
  #      # description of the group
  #      externalName: ""
  #      # external name, it should be set if your group-data-source is winbind. And the name will be used to query and match the group from
  #      # the result of winbind. If the group-data-source is basic, this field is useless.


# uncomment following section if you want to customize the port of pylon
# pylon:
#  port: 80


# if you want to enable alert-handler actions, uncomment following lines and fill the right values.
# alert-manager:
#   port: 9093 # optional, do not modify this if you do not want to change the port alert-manager is listening on
#   alert-handler: # alert-handler will only be enabled when this field is not empty
#     port: 9095 # optional, do not modify this if you do not want to change the port alert-handler is listening on
#     log-level: "info" # optional
#     pai-bearer-token: 'your-application-token-for-pai-rest-server'
#     email-configs: # email-notification will only be enabled when this field is not empty
#       admin-receiver: addr-of-admin-receiver@example.com
#       smtp-host: smtp.office365.com
#       smtp-port: 587
#       smtp-from: alert-sender@example.com
#       smtp-auth-username: alert-sender@example.com
#       smtp-auth-password: password-for-alert-sender
#   customized-routes:
#     routes:
#     - receiver: pai-email-admin-user-and-stop-job
#       match:
#         alertname: PAIJobGpuPercentLowerThan0_3For1h
#   customized-receivers:
#   - name: "pai-email-admin-user-and-stop-job"
#     actions: 
#     - email-admin
#     - email-user
#     - stop-jobs
#     - tag-jobs
#     tags: 
#     - 'stopped-by-alert-manager'


# uncomment following if you want to customize prometheus
# prometheus:
#   port: 9091 # optional, do not modify this if you do not want to change the port prometheus is listening on
#   # How frequently to scrape targets
#   scrape_interval: 30
#   customized-alerts: |
#     groups:
#     - name: customized-alerts
#       rules:
#       - alert: PAIJobGpuPercentLowerThan0_3For1h
#         expr: avg(task_gpu_percent{virtual_cluster=~"default"}) by (job_name) < 0.3
#         for: 1h
#         annotations:
#           summary: "{{$labels.job_name}} has a job gpu percent lower than 30% for 1 hour"
#           description: Monitor job level gpu utilization in certain virtual clusters.


# uncomment following if you want to change customize grafana
# grafana:
#   port: 3000


# uncomment following if you want node-exporter listen to different port
# node-exporter:
#   port: 9100


# uncomment following if you want to customeize job-exporter
# job-exporter:
#   port: 9102
#   logging-level: INFO
#   interface: eth0,eno2


# uncomment following section if you want to customize the threshold of cleaner
# cleaner:
#  threshold: 94
#  interval: 60

# uncomment following section if you want to customize the port of log-manager
# log-manager:
#  port: 9103


# uncomment following section if you want to customize the port of storage-manager
# storage-manager:
#  localpath: /share
#  security-type: AUTO
#  workgroup: WORKGROUP
#  smbuser: smbuser
#  smbpwd: smbpwd
``` 

The example config shows the config for master 10.0.0.32 and two CPU workers `10.0.0.33` and `10.0.0.34`. You should modify the config accordingly.

**You should be cautious about:**

- `mem`, `gpu`, and `cpu` info in `layout.yaml` is not used. They are legacy and you could set them to 1.
-  `tag` stands for the openPAI version.
- Settings below `hivedscheduler` : you should first read https://hzytest-pai-docs.readthedocs.io/en/latest/manual/cluster-admin/how-to-set-up-virtual-clusters.html and https://github.com/microsoft/hivedscheduler/blob/master/doc/user-manual.md to get some basic knowledge, then modify the setting accordingly. For now, please reserve at least 2 CPUs and 1G memory in your worker. For example,  the above setting use `4*5=20` CPU and `5000Mi * 4=20GiB` memory for each worker. The worker should have >= 22 CPU and >= 21GB memory.

4. Push the config and start service in the dev box container.

cluster id should be `pai`.

```
cd /pai
./paictl.py config push -p <config folder> -m service
./paictl.py service start
```
