### ISSUE TITLE
support different types of computing hardware

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#5138]
Currently, OpenPAI has support for the the most common computing device: Nvidia GPU, AMD GPU and CPU. In addition, it has the potential to support other types of device, e.g. AI computing chips.

Here's a proposal for supporting different types of computing hardware in OpenPAI.

1. Each worker machine in OpenPAI should have one ***machine model***. Machine model is a rough category for machines with differnt computing devices. It could be: `cpu-node`, `nvidia-gpu-node`, `amd-gpu-node`, `<a-certain-brand>-ai-chip-node`, ..., etc. Here we assume one worker machine should have only one kind of computing device. For example, one worker machine shouldn't have both AMD and NVIDIA GPU.  

2. For different components in OpenPAI, if they should support different types of computing device, there will be a `devices` folder in it organized as:

```
devices/
  cpu-machine/
  nvidia-gpu-machine/
  amd-gpu-machine/
  ...
```

For PAI services, they should take these files into consideration in build time. And one container will support a list of different machine models.

For other components like the deploy script, they should check these files in runtime.

The components that need change include:

- deploy script: pre checks / installation items for each machine model
- exporter: additional exporters for machine models besides nvidia gpu / cpu machine.
- rest-server: When generating pod spec, rest-server should be aware of environmental variables used by other device in addition to `NVIDIA_VISIBLE_DEVICES` and `PAI_AMD_VISIBLE_DEVICES`.

https://github.com/microsoft/pai/blob/2fb370a59387f7df5e6cec9d30d194f3af19e2d9/src/rest-server/src/models/v2/job/k8s.js#L656-L676

- scheduler: health report for computing device. This is not mandatory since node-level health check is provided by k8s already.

3. We can use `layout.yaml` to keep track of each worker's machine model. Here is an example:

```yaml
machine-sku:
  master-machine:
    model: cpu-node
    mem: 60GB
    cpu:
      vcore: 24

  gpu-machine:
   model: nvidia-gpu-node
    mem: 220GB
    cpu:
      vcore: 24
    gpu:
      type: K80
      count: 4

machine-list:
    - hostname: pai-master
      hostip: 10.0.0.1
      machine-type: master-machine
      pai-master: "true"
    - hostname: pai-worker1
      hostip: 10.0.0.2
      machine-type: gpu-machine
      pai-worker: "true"
    - hostname: pai-worker2
      hostip: 10.0.0.3
      machine-type: gpu-machine
      pai-worker: "true"
```

4. Target: Decouple OpenPAI service container and specific hardware types. One OpenPAI service container can support a list of hardware types.

**Comment by hzy46** [comment]
Detailed Work Items for this issue:

- Installation
  - [ ] P0 add a flag to use default scheduler, and not enable hived scheduler
  - [ ] P0 Refactor the code structure to run prechecks / installation items of different hardwares
    - Add a `computing_devices` folder
- Device Plugin
  - [ ] P0 Refactor the code structure to install different device plugins
    - Add a `computing_devices` folder
- Rest-server
  - [ ] P0 read `defaultComputingDeviceType` from `layout.yaml` (Use `nvidia.com/gpu` if not found)
     - Should support it in https://github.com/microsoft/pai/blob/master/src/rest-server/src/models/v2/virtual-cluster/k8s.js , https://github.com/microsoft/pai/blob/master/src/rest-server/src/models/v2/utils/frameworkConverter.js , https://github.com/microsoft/pai/blob/d0aef5dc009794b4804027b4f21c78556024d2ec/src/rest-server/src/models/v2/job/k8s.js
  - [ ] P1 support config `hivedComputingDeviceList` in https://github.com/microsoft/pai/blob/d0aef5dc009794b4804027b4f21c78556024d2ec/src/rest-server/src/models/v2/job/k8s.js
- [ ] P2 webportal
- [ ] P2 refactor `job_exporter`, `node_exporter`, `watchdog` codes to support different hardwares

**Comment by hzy46** [comment]
Test cases for rest-server:

### 1. Default Scheduler: Test the resource requirement is correctly specified in pod definition.
 
- `./paictl.py service stop -n hivedscheduler cluster-configuration rest-server`
- Modify `services-configuration.yaml`: disable hivedscheduler
- Modify `layout.yaml`: set the cluster workers' computing device type to `a.b.com/c` e.g. :

```
machine-sku:
  master-machine: # define a machine sku
    # the resource requirements for all the machines of this sku
    # We use the same memory format as Kubernetes, e.g. Gi, Mi
    # Reference: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory
    mem: 60Gi
    cpu:
      # the number of CPU vcores
      vcore: 24
  gpu-machine:
    computing-device:
      type: a.b.com/c
      model: faked
      count: 4
    mem: 220Gi
    cpu:
      vcore: 24

machine-list:
  - hostname: pai-master # name of the machine, **do not** use upper case alphabet letters for hostname
    hostip: 10.0.0.1
    machine-type: master-machine # only one master-machine supported
    pai-master: "true"
  - hostname: pai-worker1
    hostip: 10.0.0.2
    machine-type: gpu-machine
    pai-worker: "true"
  - hostname: pai-worker2
    hostip: 10.0.0.3
    machine-type: gpu-machine
    pai-worker: "true"
………………
```
- push the modified config to k8s
- `./paictl.py service start -n hivedscheduler cluster-configuration rest-server`
- submit a job from webportal
- expect there is a `a.b.com/c` resource request in the pod spec

### 2. Hived Scheduler: Test the environment varibales is set in pod spec.

-`./paictl.py service stop -n hivedscheduler cluster-configuration rest-server`
- Modify `services-configuration.yaml`: enable hivedscheduler; set `rest-server.hived-computing-device-envs` to `TEST,NVIDIA_VISIBLE_DEVICES,HIVED_VISIBLE_DEVICES`
- Modify `layout.yaml`: set the cluster workers' computing device type back to `nvidia.com/gpu`
- push the modified config to k8s
- `./paictl.py service start -n hivedscheduler cluster-configuration rest-server`
- submit a job from webportal
- In the pod, expect environment variable `TEST` is set to something like `0,1,.....`
