### ISSUE TITLE
When a job is pulling the docker image, all subsequent submitted jobs remain waiting.

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5150]
**Organization Name**:

**Short summary about the issue/question**:
When a job is pulling the docker image, all subsequently submitted jobs remain waiting.

**Brief what process you are following**:
1. Submit a job that needs to pull the image from docker hub.
2. Submit a job that has local image.
3. Job2 keeps waiting until job1 starts running.

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: v1.3.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by siaimes** [comment]
The trigger condition is that these two jobs are in the same node.

**Comment by siaimes** [comment]
Ubuntu 18.04 and OpenPAI v1.8.0 still exist this issue.

@debuggy can we can increase the priority of fixing this issue? Thanks.

**Comment by siaimes** [comment]
An 8 GPU server with 4 jobs running and 3 jobs waiting:

![image](https://user-images.githubusercontent.com/34199488/165049715-e4b0a716-a6d4-49ef-91e5-c48b56ff5d8d.png)

Pause containers are all started:

![image](https://user-images.githubusercontent.com/34199488/165050134-c2f151ed-4d87-4831-872a-cf0254ace9ab.png)

What caused the first job to get stuck in a wait state was pulling an image.

![image](https://user-images.githubusercontent.com/34199488/165050430-444345b6-ab5b-4d96-b68e-595e8307e340.png)

However, the images of the subsequent two jobs are both locally but are blocked by the first waiting job.

![image](https://user-images.githubusercontent.com/34199488/165050545-04f962e7-d519-4326-934b-af6971f53535.png)

**Comment by siaimes** [comment]
When the job is killed while pulling the image, the `kubelet` will not stop pulling the image, which causes subsequent jobs to still fail to start until the image pull is completed.

**Comment by siaimes** [comment]
There is evidence that this is not due to Kubernetes.

First, I submit a deployment that needs to pull a large image through `kubectl`:

```
root@csip-dev-box-test:/cluster-configuration/pod# cat pod-0.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-0
spec:
  selector:
    matchLabels:
      run: pod-0
  replicas: 1
  template:
    metadata:
      labels:
        run: pod-0
    spec:
      containers:
      - name: pod-0
        image: siaimes/pytorch1.10.0:v1.0.1
      nodeName: csip-095
      restartPolicy: Always
```

The corresponding node can see that the job is pulling the image:

![image](https://user-images.githubusercontent.com/34199488/165060241-904a9003-d883-4719-b80a-510fa4bfa54d.png)

Then I submit a job with a local image:

```
root@csip-dev-box-test:/cluster-configuration/pod# cat pod-1.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-1
spec:
  selector:
    matchLabels:
      run: pod-1
  replicas: 1
  template:
    metadata:
      labels:
        run: pod-1
    spec:
      containers:
      - name: pod-1
        image: nginx:1.15
      nodeName: csip-095
      restartPolicy: Always
root@csip-dev-box-test:/cluster-configuration/pod#
```
The job ran successfully:

![image](https://user-images.githubusercontent.com/34199488/165060682-d2621f9e-9f81-4b6c-ba83-144f5a9d1f8b.png)

**Comment by siaimes** [comment]
> https://github.com/microsoft/pai/blob/1f5f52d2ea885b6034f181d487c4960330474d97/src/rest-server/src/models/v2/job/k8s.js#L482

Modify the `imagePullPolicy` of `pod-1` to `IfNotPresent` can solve this issue, can we change this line to:

```
    imagePullPolicy: 'IfNotPresent', 
```

**Comment by siaimes** [comment]
If it is really necessary to use `Always`, then my PR may be a good solution. By the way, it also brings a good bonus, that is, the log of pulling the image is delegated to the user, which reduces the difficulty of user to diagnosis jobs.

![image](https://user-images.githubusercontent.com/34199488/165318479-deaa83d9-f69e-47b7-91d6-208b65da7a6d.png)

**Comment by siaimes** [comment]
Two candidate solutions:
1. Modify the kubelet startup flag `SerializeImagePulls` to `false`;
2. Modify the `imagePullPolicy` of `pai` from `Always` to `IfNotPresent`.

**Comment by Binyang2014** [comment]
I prefer to set `SerializeImagePulls` to `false`. You can add a configuration in this file https://github.com/microsoft/pai/blob/master/contrib/kubespray/quick-start/openpai.yml.template. And add some doc to let customer config this option by their own.

**Comment by siaimes** [comment]
# The source of the issue

## The flag is defined here

https://github.com/kubernetes/kubernetes/blob/06e107081e4e0182efb9daa0daf7f2ae12272704/cmd/kubelet/app/options/options.go#L485

```go
	fs.BoolVar(&c.SerializeImagePulls, "serialize-image-pulls", c.SerializeImagePulls, "Pull images one at a time. We recommend *not* changing the default value on nodes that run docker daemon with version < 1.9 or an Aufs storage backend. Issue #10959 has more details.")
```

## Can change it by using kubespray

https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/docs/vars.md


```yaml
kubelet_custom_flags:
  - "--serialize-image-pulls=false"
```

# Solution

## add config to contrib/kubespray/config/config.yaml

```yaml
openpai_kubespray_extra_var:
  kubelet_custom_flags:
    serialize-image-pulls: false
```


##  Update `contrib/kubespray/quick-start/openpai.yml.template` to process `config.yaml` with this situation

https://github.com/microsoft/pai/blob/e41df9f0b945ca3572d990d6f669a1e5ca496592/contrib/kubespray/quick-start/openpai.yml.template#L409-L413
