### ISSUE TITLE
replace master.csv / worker.csv by layout.yaml

### ISSUE THREAD

**Issue by mydmdm** [microsoft/pai#5151]
## Motivation
Currently we use `master.csv` and `worker.csv` to describe the machine information when installation. However, it has some issues like
- `master.csv` and `worker.csv` is one-time during installation and then `layout.yaml` is used for other purpose 
- strict format requirement, e.g., disallowing space
- limited representation capability
- duplication, users must configure more than one places
  - e.g. during installation time: `worker.csv`, `master.csv`; adding/removing nodes: `hosts.yml`, `layout.yaml`, `services-configuration.yaml`; uninstallation time: `hosts.yml`, `openpai.yml`

### Goal
- let user write only once when installing and modifying OpenPAi services
- better support diverse types of computing hardware

## Proposal

We assume that one worker machine in OpenPAI could have only one kind of computing device. For example, one worker machine shouldn't have both AMD and NVIDIA GPU.  We can use `layout.yaml` to keep track of each machine's information and device. Here is an example:

```yaml
machine-sku:
  master-machine:
    mem: 60GB
    cpu:
      vcore: 24

  gpu-machine:
   computing-device: 
      type: nvidia.com/gpu
      model: K80
      count: 4
    mem: 220GB
    cpu:
      vcore: 24

machine-list:
    - hostname: pai-master
      hostip: 10.0.0.1
      machine-type: master-machine
      pai-master: "true"
    - hostname: pai-worker1
      hostip: 10.0.0.2
      machine-type: gpu-machine
      pai-worker: "true"
    - hostname: pai-worker2
      hostip: 10.0.0.3
      machine-type: gpu-machine
      pai-worker: "true"
```
