### ISSUE TITLE
STDOUT/STDERR only get "Failed to fetch"

### ISSUE THREAD

**Issue by ReyRen** [microsoft/pai#5159]
**Organization Name**:

**Short summary about the issue/question**:
The `stdout` and `stderr` show "Failed to fetch" when I use  my own image to do the training test. I'm sure the command I specified in .yaml would get tons of logs to stdout, however, it would stuck at "USER COMMAND START" when I use `kubectl logs -f  podID ` to check the stdout logs and "USER COMMAND END" after a while. And the openPAI stdout/stderr get "Failed to fetch"

submit a job

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
v1.3.0
- Cloud provider or hardware configuration:
local env
- OS (e.g. from /etc/os-release):
Ubuntu 18.04
- Kernel (e.g. `uname -a`):
Linux node4 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
nvidia GPU
- Others:
yaml file:
```
protocolVersion: 2
name: hello-world-job10
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'whoami179/tensorflow-tb-test-data:test'
    name: docker_image_0
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: -1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 1
      cpu: 5
      memoryMB: 15253
    commands:
      - cd /root/hymenoptera
      - python train.py
defaults:
  virtualCluster: default
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
  hivedScheduler:
    taskRoles:
      taskrole:
        skuNum: 1
        skuType: DT
```

**Anything else we need to know**:
Thanks in advance
