### ISSUE TITLE
Add / Remove Nodes with `layout.yaml`

### ISSUE THREAD

**Issue by suiguoxin** [microsoft/pai#5167]
## Target
allow users to add / remove nodes with `layout.yaml` instead of `hosts.yml`.

### add nodes: 
Step 1: add config
add the corresponding nodes in to the `machine-list` field in `layout.yaml`
```yaml
machine-list:
  - hostname: a
    hostip: x.x.x.x
    machine-type: xxx-sku
    pai-worker: "true"
- hostname: b
    hostip: x.x.x.x
    machine-type: xxx-sku
    pai-worker: "true"
```
Step 2: add nodes to k8s
``` bash
./paictl scale --nodes "node=a,b"
```
in this step, we will:
- call `ansible-playbook` to add the nodes to k8s

Step 3: 
Modify HiveD config in `services-configuration.yaml`, restart services: `cluster-configuration` `hivedscheduler` `rest-server` 

**Questions:** support add node of new sku ?

### remove nodes: 

Step 1: remove nodes from k8s
``` bash
./paictl remove-node --nodes "node=a,b"
```
in this step, we will:
- call `ansible-playbook` to remove the nodes from k8s
- **modify `layout.yaml`** ?

Step 3: 
Modify HiveD config in `services-configuration.yaml`, restart services: `cluster-configuration` `hivedscheduler` `rest-server`
