### ISSUE TITLE
Submit job failed due to  Pod spec contains permanent error 

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#5215]
**Organization Name**:
advantech

**Short summary about the issue/question**:
Submit job failed due to  Pod spec contains permanent error 
Job spec
```
taskRoles:
  jupyter:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: -1
    taskRetryCount: 0
    dockerImage: jupyter_image
    extraContainerOptions:
      shmMB: 500
    resourcePerInstance:
      cpu: 1
      memoryMB: 500
      gpu: 1
      ports:
        jupyter: 1
        tensorboard: 1
        grpc: 1
```

Exit Reason
```
Exit Code:
-200
Exit Type:
USER_FAILURE
Exit Reason:
Pod spec contains permanent error
Failed to create Pod: {"ErrStatus":{"metadata":{},"status":"Failure","message":"pods \"7664060197ec7e87bf21d4bd73857b42-jupyter-0\" is forbidden: failed quota: ensaas-default-resourcequota: must specify limits.cpu,limits.memory,requests.cpu,requests.memory","reason":"Forbidden","details":{"name":"7664060197ec7e87bf21d4bd73857b42-jupyter-0","kind":"pods"},"code":403}}
Exit Solutions:
Check diagnostics and revise your job config
```

namespace quota
```
root@ainode:~# kubectl describe quota
Name:                       ensaas-default-resourcequota
Namespace:                  default
Resource                    Used     Hard
--------                    ----     ----
limits.cpu                  2        40
limits.ephemeral-storage    1Gi      105Gi
limits.memory               21888Mi  323840Mi
pods                        17       110
requests.cpu                2600m    4300m
requests.ephemeral-storage  1Gi      5888Mi
requests.memory             20096Mi  21248Mi
requests.nvidia.com/gpu     0        0
root@ainode:~#
```

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
v1,0,1
- Cloud provider or hardware configuration:
OpenStack
- OS (e.g. from /etc/os-release):
16.04.6

**Anything else we need to know**:
