### ISSUE TITLE
[pai sku conversion] sku conversion not work on multiple taskrole config without sku config

### ISSUE THREAD

**Issue by SwordFaith** [microsoft/pai#5237]
**What would you like to be added**:

At multiple taskrole scenery, it will be better to convert each taskrole resource to sku.

**Why is this needed**:

Without conversion to second taskrole sku, webportal will display strange warning info as following image:
![image](https://user-images.githubusercontent.com/18397468/104088192-f21a0000-529f-11eb-96c7-77ec94147f6b.png)
And the yaml state is:
```YAML
protocolVersion: 2
name: horovod_pytorch_78a47051
description: >
  # Horovod PyTorch Job Template

  This is a distributed synthetic benchmark for Horovod with PyTorch backend
  running on OpenPAI.

  It runs [Horovod with Open
  MPI](https://github.com/horovod/horovod/blob/master/docs/mpirun.rst).
contributor: OpenPAI
type: job
jobRetryCount: 0
prerequisites:
  - protocolVersion: 2
    name: horovod_official
    type: dockerimage
    contributor: Horovod
    uri: 'horovod/horovod:0.16.4-tf1.12.0-torch1.1.0-mxnet1.4.1-py3.5'
parameters:
  model: resnet50
  batchsize: 64
  nccl: '-x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=eth0'
taskRoles:
  master:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: 1
    taskRetryCount: 0
    dockerImage: horovod_official
    resourcePerInstance:
      cpu: 20
      memoryMB: 200000
      gpu: 4
    commands:
      - sleep 10
      - >-
        mpirun --allow-run-as-root -np 8 -H master-0:4,worker-0:4 -bind-to none
        -map-by slot -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_exclude
        lo,docker0 <% $parameters.nccl %> -x PATH -x LD_LIBRARY_PATH python
        pytorch_synthetic_benchmark.py --model <% $parameters.model %>
        --batch-size <% $parameters.batchsize %>
  worker:
    instances: 1
    completion:
      minFailedInstances: 1
    taskRetryCount: 0
    dockerImage: horovod_official
    resourcePerInstance:
      cpu: 16
      memoryMB: 16384
      gpu: 4
    commands:
      - sleep infinity
defaults:
  virtualCluster: default
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
        sshbarrier: true
  hivedScheduler:
    taskRoles:
      master:
        skuNum: 4
        skuType: K80
      worker:
        skuNum: 4
        skuType: null
```

This warning can work around by click other taskroles in webportal or fill out sku config for each task role.

**Without this feature, how does the current module work**:
It shows warning as above.

**Components that may involve changes**:
I think this is part of webportal function.
