### ISSUE TITLE
The log-manager cannot work well with Nginx reverse proxy.

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5260]
**Organization Name**:

**Short summary about the issue/question**:
The marketplace cannot work well with Nginx reverse proxy.

**Brief what process you are following**:
My master node does not have an Internet IP, and I am configuring it to be accessible by clients on the Internet. So I configured nginx on a server located in a demilitarized zone.

My nginx configuration file for openpai is as follows:
```
server {

	# SSL configuration
	listen 443 ssl;
        
	server_name openpai.domain.com;

        ssl_certificate "/path/to/certificate.crt";
	ssl_certificate_key "/path/to/private.key";

	location / {
            proxy_pass https://172.17.1.100;
	}

}
```

Everything is behaving normally, except for the marketplace.

The market cannot be opened on the Internet, and if I am on the LAN, I can open the market, but the lock in front of the URL of the Chrome browser turns red (it was black before accessing the market).

I know this is because I wrote the IP instead of the domain name for the marketplace part in the `services-configuration.yaml` configuration file like is.

```
webportal:
  server-port: 9286
  plugins:
  - title: Marketplace
    uri: https://172.17.1.100/marketplace/plugin.js
    config:
      repo: Microsoft/pai

marketplace-webportal:
  marketplace_api_uri: https://172.17.1.100/marketplace/api
```

Because when using Nginx as a reverse proxy, Nginx will rewrite the host filed in the web page to the current host. However, most of the host filed of openpai can be modified except for the marketplace. Therefore, I think that the source code of the marketplace may violate some regulations.

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: v1.4.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):  Ubuntu 16.04.7 LTS
- Kernel (e.g. `uname -a`): Linux devbox 4.15.0-123-generic #126~16.04.1-Ubuntu SMP Wed Oct 21 13:48:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by siaimes** [comment]
Forgive my carelessness. Just after I submitted this issue, I saw that the key in the configuration file was uri instead of url, so the problem was solved. The new configuration file is as follows.

```
webportal:
  server-port: 9286
  plugins:
  - title: Marketplace
    uri: /marketplace/plugin.js
    config:
      repo: Microsoft/pai

marketplace-webportal:
  marketplace_api_uri: /marketplace/api
```
