### ISSUE TITLE
K8s API server's cert need renew each year

### ISSUE THREAD

**Issue by yiyione** [microsoft/pai#5334]
The k8s API server's cert will expire every year, and will cause OpenPAI cluster not available.
Certificate Management with kubeadm:
https://v1-16.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#automatic-certificate-renewal

![image](https://user-images.githubusercontent.com/17357108/109600953-07e9ca00-7b59-11eb-9128-0455a305b4d0.png)

### Todo
- [ ] Document this requirement in the repo
- [ ] Add warning for the cert expire

**Comment by Binyang2014** [comment]
refer: https://github.com/kubernetes/kubeadm/issues/581#issuecomment-471575078

**Comment by yiyione** [comment]
Test case:
1. setup the alert-manager to enable the `email-admin` action (change the `admin-receiver` to a test address)
2. change the `schedule` and `alert-residual-days` in `alert-manager.cert-expiration-checker` from `services-configuration.yaml` to trigger the alert:
    ```yaml
    cert-expiration-checker:
      schedule: '* * * * *' # every minute
      alert-residual-days: 365 # always trigger
      cert-path: '/etc/kubernetes/ssl' # the k8s cert path in master node
    ```
3. use kubectl get pods to check whether the `cert-expiration-checker` cronjob be triggered
4. check the alert email or the logs from alert handler.
