### ISSUE TITLE
Inform the user when job fails

### ISSUE THREAD

**Issue by suiguoxin** [microsoft/pai#5337]
## Motivation
Some jobs may fail unexpectedly. 
If the users can be informed when the jobs fail, the users will be able to handle the issue in time.
This will save the users from checking their job status all the time.

## Design
- enable this feature in job protocal
```yaml
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
  hivedScheduler:
    taskRoles:
      taskrole:
        skuNum: 1
        skuType: GENERIC-WORKER
  **informAtFailure: true**
```
