### ISSUE TITLE
how to access my own gitlab source when running job

### ISSUE THREAD

**Issue by HaoLiuHust** [microsoft/pai#5368]
I have some problem to connect to gitlab to clone the code, so I want to test to clone code from our company's gitlab. But I can only clone code with SSH, how to do it in the job?

**Comment by fanyangCS** [comment]
I am not sure I understand your question. Do you mean you cannot access gitlab from within the job container? Can you access other site in the container? Maybe you should check the CNI deployment in the k8s.

**Comment by HaoLiuHust** [comment]
because of the GFW... clone code from github could be slow or failed, and for security, I want to clone code from company's private gitlab, but I can not clone from it without SSH security key, how could I do this?

**Comment by Binyang2014** [comment]
Hi @HaoLiuHust. Before clone code, you need to add your private key to ssh-agent.
Please refer https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent

For the private key, you can put it into secret field.
And refer the secret field in the command.

Please make sure your container has ssh tools

example:
``` yaml
protocolVersion: 2
name: job
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'openpai/standard:python_3.6-pytorch_1.2.0-gpu'
    name: docker_image_0
secrets:
  ssh-key: |
    -----BEGIN RSA PRIVATE KEY-----
   <your key>
    -----END RSA PRIVATE KEY-----
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 1
      cpu: 5
      memoryMB: 51200
    commands:
      - echo  "<% $ssh-ke.ssh-key %>" > key-file
      - ssh-add ./key-file
      - git clone ....
```
