### ISSUE TITLE
Update hived request generation in rest-server

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#5419]
new schema in OpenPAI job protocol:

```yaml
extras:
  hivedscheduler:
    jobPriorityClass: crit | prod | test (default) | oppo
    gangReleaseEnable: false (default) | true
    lazyPreemptionEnable: false (default) | true
    ignoreK8sSuggestedNodes: false (default) | true 
    taskRoles:
     <taskrole_name>:
        pinnedCellId: string | null (default)
        # if resourcePerInstance doesn't exist, we should calculate it from 
        # config.taskroles.<taskrole_name>.resourcePerInstance, and use null as skuType
        resourcePerInstance:
          skuNum: number 
          skuType: string | null (default)
       withinOne: string | null (default)
       # for now, MUST be config.taskroles.<taskrole_name>.instances
       # if null, treat it as config.taskroles.<taskrole_name>.instances
       minGangInstance: number | null
    taskRoleGroups:
        # we don't allow single group: length of taskRoles must be > 1 
        # we don't allow overlap
      - taskRoles: [master, worker]
         withinOne: string | null
         # for now, MUST be true; if null, treat it as null
         gang: true | null
```

Remaining question: will `extras.gangAllocation` have any effect?
