### ISSUE TITLE
can not start job-exporter

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5444]
**Organization Name**:

**Short summary about the issue/question**: When I delete one of my machine in the default virtual cluster and restart openpai. The service job-exporter can not start successfully.

here is my configures:
```
hivedscheduler:
  config: |
    physicalCluster:
      skuTypes:
        CPU:
          cpu: 0
          cpu: 1
          memory: 8Gi
        K80:
          gpu: 1
          cpu: 6
          memory: 64Gi
        RTX2080Ti:
          gpu: 1
          cpu: 6
          memory: 15Gi
        K40:
          gpu: 1
          cpu: 15
          memory: 30Gi
        GTX1080Ti:
          gpu: 1
          cpu: 6
          memory: 28Gi
        TITANXp32G:
          gpu: 1
          cpu: 6
          memory: 28Gi
        TITANXp64G:
          gpu: 1
          cpu: 6
          memory: 60Gi
      cellTypes:
        CPU-NODE:
          childCellType: CPU
          childCellNumber: 15
          isNodeLevel: true
        CPU-NODE-POOL:
          childCellType: CPU-NODE
          childCellNumber: 1
        K80-NODE:
          childCellType: K80
          childCellNumber: 4
          isNodeLevel: true
        K80-NODE-POOL:
          childCellType: K80-NODE
          childCellNumber: 1
        RTX2080Ti-NODE:
          childCellType: RTX2080Ti
          childCellNumber: 8
          isNodeLevel: true
        RTX2080Ti-NODE-POOL:
          childCellType: RTX2080Ti-NODE
          childCellNumber: 1
        K40-NODE:
          childCellType: K40
          childCellNumber: 2
          isNodeLevel: true
        K40c-NODE-POOL:
          childCellType: K40-NODE
          childCellNumber: 1
        K40m-NODE-POOL:
          childCellType: K40-NODE
          childCellNumber: 1
        GTX1080Ti-NODE:
          childCellType: GTX1080Ti
          childCellNumber: 1
          isNodeLevel: true
        GTX1080Ti1-NODE-POOL:
          childCellType: GTX1080Ti-NODE
          childCellNumber: 1
        GTX1080Ti2-NODE-POOL:
          childCellType: GTX1080Ti-NODE
          childCellNumber: 1
        TITANXp32G-NODE:
          childCellType: TITANXp32G
          childCellNumber: 1
          isNodeLevel: true
        TITANXp32G1-NODE-POOL:
          childCellType: TITANXp32G-NODE
          childCellNumber: 1
        TITANXp32G2-NODE-POOL:
          childCellType: TITANXp32G-NODE
          childCellNumber: 1
        TITANXp32G3-NODE-POOL:
          childCellType: TITANXp32G-NODE
          childCellNumber: 1
        TITANXp32G4-NODE-POOL:
          childCellType: TITANXp32G-NODE
          childCellNumber: 1
        TITANXp32G5-NODE-POOL:
          childCellType: TITANXp32G-NODE
          childCellNumber: 1
        TITANXp32G6-NODE-POOL:
          childCellType: TITANXp32G-NODE
          childCellNumber: 1
        TITANXp64G-NODE:
          childCellType: TITANXp64G
          childCellNumber: 1
          isNodeLevel: true
        TITANXp64G1-NODE-POOL:
          childCellType: TITANXp64G-NODE
          childCellNumber: 1
        TITANXp64G2-NODE-POOL:
          childCellType: TITANXp64G-NODE
          childCellNumber: 1
        TITANXp64G3-NODE-POOL:
          childCellType: TITANXp64G-NODE
          childCellNumber: 1
      physicalCells:
      - cellType: CPU-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-001
      - cellType: K80-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-001
      - cellType: RTX2080Ti-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-090
      - cellType: K40c-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-094
      - cellType: K40m-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-095
      - cellType: TITANXp32G1-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-005
      - cellType: TITANXp32G2-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-006
      - cellType: TITANXp32G3-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-007
      - cellType: TITANXp32G4-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-008
      - cellType: TITANXp32G5-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-102
      - cellType: TITANXp32G6-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-103
      - cellType: TITANXp64G1-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-009
      - cellType: TITANXp64G2-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-010
      - cellType: GTX1080Ti1-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-104
      - cellType: GTX1080Ti2-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-014
      - cellType: TITANXp64G3-NODE-POOL
        cellChildren:
        - cellAddress: rzxt-openpai-106
    virtualClusters:
      default:
        virtualCells:
        - cellType: CPU-NODE-POOL.CPU-NODE
          cellNumber: 1
      k40c:
        virtualCells:
        - cellType: K40c-NODE-POOL.K40-NODE
          cellNumber: 1
      k40m:
        virtualCells:
        - cellType: K40m-NODE-POOL.K40-NODE
          cellNumber: 1
      k80:
        virtualCells:
        - cellType: K80-NODE-POOL.K80-NODE
          cellNumber: 1
      rtx2080ti:
        virtualCells:
        - cellType: RTX2080Ti-NODE-POOL.RTX2080Ti-NODE
          cellNumber: 1
      gtx1080ti1:
        virtualCells:
        - cellType: GTX1080Ti1-NODE-POOL.GTX1080Ti-NODE
          cellNumber: 1
      gtx1080ti2:
        virtualCells:
        - cellType: GTX1080Ti2-NODE-POOL.GTX1080Ti-NODE
          cellNumber: 1
      titanxp32g1:
        virtualCells:
        - cellType: TITANXp32G1-NODE-POOL.TITANXp32G-NODE
          cellNumber: 1
      titanxp32g2:
        virtualCells:
        - cellType: TITANXp32G2-NODE-POOL.TITANXp32G-NODE
          cellNumber: 1
      titanxp32g3:
        virtualCells:
        - cellType: TITANXp32G3-NODE-POOL.TITANXp32G-NODE
          cellNumber: 1
      titanxp32g4:
        virtualCells:
        - cellType: TITANXp32G4-NODE-POOL.TITANXp32G-NODE
          cellNumber: 1
      titanxp32g5:
        virtualCells:
        - cellType: TITANXp32G5-NODE-POOL.TITANXp32G-NODE
          cellNumber: 1
      titanxp32g6:
        virtualCells:
        - cellType: TITANXp32G6-NODE-POOL.TITANXp32G-NODE
          cellNumber: 1
      titanxp64g1:
        virtualCells:
        - cellType: TITANXp64G1-NODE-POOL.TITANXp64G-NODE
          cellNumber: 1
      titanxp64g2:
        virtualCells:
        - cellType: TITANXp64G2-NODE-POOL.TITANXp64G-NODE
          cellNumber: 1
      titanxp64g3:
        virtualCells:
        - cellType: TITANXp64G3-NODE-POOL.TITANXp64G-NODE
          cellNumber: 1
```

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: v1.6.0
- OpenPAI version: v1.6.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.0-194-generic
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:
