### ISSUE TITLE
webportal do not work for v1.6.0

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5455]
**Organization Name**:

**Short summary about the issue/question**:
After config marketplace based on [this comment](https://github.com/microsoft/pai/pull/5066#issuecomment-729334425). The link [https://master_ip/marketplace/api/](https://master_ip/marketplace/api/) and [https://master_ip/marketplace/plugin.js](https://master_ip/marketplace/plugin.js) can work well.

but webportal config based on this [how to](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-customize-cluster-by-plugins.html) does not work.

related section of service file.

```
cluster:
  common:
    cluster-id: pai
    cluster-type: k8s
    k8s-rbac: "true"
    job-history: "true"
    data-path: "/datastorage"
    qos-switch: "false"
    docker-data-root: "/mnt/docker"
    marketplace: "true"
```

```
webportal:
  server-port: 9286

  plugins:
  - title: Marketplace
    uri: /marketplace/plugin.js

marketplace-webportal:
  marketplace_api_uri: https://master_ip/marketplace/api
```

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version: v1.6.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by siaimes** [comment]
![image](https://user-images.githubusercontent.com/34199488/116212792-cac83f80-a777-11eb-8b5e-c97dc5b93146.png)

**Comment by debuggy** [comment]
could you start a dev-box, go to `/pai` and run commands: 
`paictl.py service stop -n marketplace-db marketplace-restserver marketplace-webportal` 
`paictl.py service start -n marketplace-db marketplace-restserver marketplace-webportal` 

to see the results? It is recommended to use dev-box manage the pai cluster after using quick-start deployment.

**Comment by siaimes** [comment]
> could you start a dev-box, go to `/pai` and run commands:
> `paictl.py service stop -n marketplace-db marketplace-restserver marketplace-webportal`
> `paictl.py service start -n marketplace-db marketplace-restserver marketplace-webportal`
> 
> to see the results? It is recommended to use dev-box manage the pai cluster after using quick-start deployment.

I have run these two commands, and these three containers are already working. The link https://master_ip/marketplace/api/ and https://master_ip/marketplace/plugin.js can return files successfully.

My problem is that the plugin is not displayed on the homepage.

And, this [issue](https://github.com/microsoft/pai/issues/5457) is more urgent, can you take a look, thank you.

**Comment by yiyione** [comment]
> > could you start a dev-box, go to `/pai` and run commands:
> > `paictl.py service stop -n marketplace-db marketplace-restserver marketplace-webportal`
> > `paictl.py service start -n marketplace-db marketplace-restserver marketplace-webportal`
> > to see the results? It is recommended to use dev-box manage the pai cluster after using quick-start deployment.
> 
> I have run these two commands, and these three containers are already working. The link https://master_ip/marketplace/api/ and https://master_ip/marketplace/plugin.js can return files successfully.
> 
> My problem is that the plugin is not displayed on the homepage.
> 
> And, this [issue](https://github.com/microsoft/pai/issues/5457) is more urgent, can you take a look, thank you.

Looks like you have resolve #5457, thanks for your answer , and we are going to fix the ansible  version in deployment (or you can submit PRs if you want).
And for this issue can you try to visit the page `https://<master_ip>/plugin.html?index=0` ?

**Comment by yiyione** [comment]
is there any error in console after Press 'F12' & refresh the page ?

**Comment by siaimes** [comment]
> is there any error in console after Press 'F12' & refresh the page ?

![image](https://user-images.githubusercontent.com/34199488/116343891-ed119a00-a817-11eb-8f11-5603e488c868.png)

**Comment by yiyione** [comment]
Looks like the configuration of webportal plugin miss the `id`, can you try to add an id like this:
```yaml
webportal:
  server-port: 9286

  plugins:
  - id: marketplace 
    title: Marketplace
    uri: /marketplace/plugin.js
```
