### ISSUE TITLE
Add SKU quota for each user respectively.

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5503]
**What would you like to be added**: I request a feature that restricts the maximum number of graphics cards that can be used simultaneously for each user respectively.

**Why is this needed**: At present, when a user submits a job to a virtual cluster, as long as the cluster has free resources, openpai will immediately allocate resources for the job. If our team has enough graphics cards, this is not a problem, but when the number of graphics cards is limited, there will be a user who owns all the graphics cards, while other users cannot get a single card. However, we can't let users wait until the previous task is over before submitting a new task, which will lose a lot of flexibility.

**Without this feature, how does the current module work**:

**Components that may involve changes**:

**Comment by suiguoxin** [comment]
Hi @siaimes , thanks for the proposal. 

In OpenPAI, we basically use virtual clusters to manage the quota of users & groups. If you don't want the user to use too many cards, you can divide the cluster into small VCs and assign the user only one of them.

For the feature you proposed, I'll also suggest to implement it using [customized alerts](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-use-alert-system.html#how-to-add-customized-alerts) and [customized-actions](https://openpai.readthedocs.io/en/latest/manual/cluster-admin/how-to-use-alert-system.html#how-to-add-customized-actions).

For example, you can define a customized alert :
```
prometheus:
  customized-alerts: |
    groups:
    - name: customized-alerts
      rules:
      - alert: UserUsingTooManyGPUs
        expr: count by (username) (task_gpu_percent) > 8
        for: 1h
        labels:
          severity: warn
        annotations:
          summary: "{{$labels.username}} has more than 8 GPUs in use."
```

You can use the existing actions or implement customized action to handle this alert.
