### ISSUE TITLE
When TensorBoard is enabled, user commands will not be executed.

### ISSUE THREAD

**Issue by siaimes** [microsoft/pai#5555]
**Organization Name**: fzu

**Short summary about the issue/question**:

When tensorboard is enabled, user commands are not executed.

**Brief what process you are following**:

The only difference from other jobs is whether TensorBoard is been enabled.

![image](https://user-images.githubusercontent.com/34199488/125164152-62f49300-e1c3-11eb-8a62-bca69f402567.png)

Then, the user command will not be executed, and the job will not automatically be terminated.

From the runtime log, tensorboard does not seem to be running in the background.
```
[Sat Jul 10 12:11:04 UTC 2021] [openpai-runtime] TensorFlow installation not found - running with reduced feature set.
[Sat Jul 10 12:11:05 UTC 2021] [openpai-runtime] TensorFlow installation not found - running with reduced feature set.
[Sat Jul 10 12:11:05 UTC 2021] [openpai-runtime] 
[Sat Jul 10 12:11:05 UTC 2021] [openpai-runtime] NOTE: Using experimental fast data loading logic. To disable, pass
[Sat Jul 10 12:11:05 UTC 2021] [openpai-runtime] "--load_fast=false" and report issues on GitHub. More details:
[Sat Jul 10 12:11:05 UTC 2021] [openpai-runtime] https://github.com/tensorflow/tensorboard/issues/4784
[Sat Jul 10 12:11:05 UTC 2021] [openpai-runtime] 
[Sat Jul 10 12:11:06 UTC 2021] [openpai-runtime] TensorBoard 2.6.0a20210628 at http://csip-107:12719/ (Press CTRL+C to quit)
```

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:  `v1.6.0`
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
```
- NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`): 
```
Linux csip-107 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 ```
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by Binyang2014** [comment]
Can you share your docker image and commands?

**Comment by siaimes** [comment]
> Can you share your docker image and commands?

https://github.com/siaimes/pytorch1.9.0/blob/main/Dockerfile

Any command will get the same result.

For example
```
sleep 1d
```

If I do not enable TensorBoard, `ps -aux` will see a `sleep` process in the container. But after enabling TensorBoard, there is no such process.

**Comment by siaimes** [comment]
```
protocolVersion: 2
name: Interpreter_9cd99312
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'siaimes/pytorch1.9.0:v1.0.0'
    name: docker_image_0
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 1
      cpu: 6
      memoryMB: 63488
    commands:
      - sleep 1d
defaults:
  virtualCluster: rtx3090
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
        userssh:
          type: custom
          value: ''
    - plugin: teamwise_storage
      parameters:
        storageConfigNames:
          - csip-091
          - share
    - plugin: tensorboard
      parameters:
        port: 12719
        logdir:
          path: /mnt/tensorboard
  hivedScheduler:
    taskRoles:
      taskrole:
        skuNum: 1
        skuType: gpu-machine-rtx3090
```
