### ISSUE TITLE
Glusterfs cannot set up a read-only storage in OpenPAI, v1.7.0

### ISSUE THREAD

**Issue by DC-y** [microsoft/pai#5565]
**How to reproduce it**:
Set up a Glusterfs ReadOnlyMany PV and corresponding PVC by:
```yaml
# Gluster PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: data
    readOnly: true
---
# Gluster PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-storage
spec:
  accessModes:
  - ReadOnlyMany
  resources:
     requests:
       storage: 20Gi
```
However its access mode is RW:

![微信图片_20210715161824](https://user-images.githubusercontent.com/18099933/125754137-2c0d974b-6929-45fe-a049-806c82bf0753.png)

 I have no idea how to resolve it. Could you give me a help?

**OpenPAI Environment**:
- OpenPAI version: v1.7.0  
- Cloud provider or hardware configuration: gpu servers   
- OS (e.g. from /etc/os-release): Ubuntu 16.04  
- Kernel (e.g. `uname -a`):  4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux   
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:
