### ISSUE TITLE
Job-exporter crash due to Liveness probe failed on CPU worker

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#5570]
**Organization Name**:
Advantech

**Short summary about the issue/question**:
Job-exporter crash due to nvidia-smi on CPU worker

**Brief what process you are following**:
1. Use openpai 0.10.1 version
2. Create the following layout for deployment
```
# If corresponding values aren't be set in the machine list, the default value will be filled in.

# kubernetes api server and dashboard host
kubernetes:
  api-servers-url: http://192.168.1.104:8080
  dashboard-url: http://192.168.1.104:9090

# TODO please modify it according to your own hardware
#machine-sku:
#  GENERIC:
#    mem: 1
#    gpu:
#      type: generic
#      count: 1
#    cpu:
#      vcore: 1
#    os: ubuntu16.04
machine-sku:
  GENERIC:
    mem: 1
    cpu:
      vcore: 1
    os: ubuntu16.04

machine-list:
  - dashboard: "true"
    docker-data: "/var/lib/docker"
    etcdid: "etcdid1"
    hostip: "192.168.1.104"
    hostname: "master0"
    k8s-role: "master"
    machine-type: "GENERIC"
    nodename: "192.168.1.104"
    pai-master: "true"
    password: "advantechAIFS"
    ssh-port: "22"
    username: "root"
    zkid: "1"

  - docker-data: "/var/lib/docker"
    hostip: "192.168.1.200"
    hostname: "ubuntu"
    k8s-role: "worker"
    machine-type: "GENERIC"
    nodename: "192.168.1.200"
    pai-worker: "true"
    password: "advantechAIFS"
    ssh-port: "22"
    username: "root"
```
3. Start k8s, push config and start openpai service
4. Job-exporter crash with the following log and event
- job-exporter logs on worker
```
2021-07-20 06:54:27,239 - WARNING - MainThread - main.py:92 - failed to find gpu count from config {'nodes': {}}
2021-07-20 06:54:27,243 - INFO - MainThread - network.py:244 - didn't find correct network interface in this node, configured eth0,eno2, found {'lo': '127.0.0.1', 'enp5s0': '192.168.1.200', 'enp6s0': '192.168.123.13', 'docker0': '172.17.0.1', 'virbr0': '192.168.122.1', 'br0': '192.168.1.100'}

```

 job-exporter k8s pod events on worker
```
Events:
  Type     Reason     Age                    From                    Message
  ----     ------     ----                   ----                    -------
  Warning  Unhealthy  7m43s (x44 over 82m)   kubelet, 192.168.1.200  Liveness probe failed: Get http://192.168.1.200:9102/healthz: dial tcp 192.168.1.200:9102: getsockopt: connection refused
  Warning  BackOff    2m58s (x225 over 75m)  kubelet, 192.168.1.200  Back-off restarting failed container
root@devbox:/pai#
```

**How to reproduce it**:
Redeploy with the same config, and the job-exporter will enter crash status while deployment is done.

**OpenPAI Environment**:
- OpenPAI version:
0.10.1
- Cloud provider or hardware configuration:
KVM VM
- OS (e.g. from /etc/os-release):
ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
Pure CPU worker
- Others:

**Anything else we need to know**:
devbox and master are on KVM VMs and worker on host.
