### ISSUE TITLE
How to disable instance  retry?

### ISSUE THREAD

**Issue by DC-y** [microsoft/pai#5615]
I have disable task retry, but instance retry sometimes happend. 
How can I disable instance retry?
My config is set by
```
protocolVersion: 2
name: fuxxxxxxxxxx
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'xxxxxxxxxxxxxxx'
    name: docker_image_0
    auth:
      username: xxxxxxx
      password: <% $secrets.docker_password_0 %>
      registryuri: 'xxxxxxxxxx'
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: -1
    taskRetryCount: 0
```

retry happend ....

![Lark20210909-140922](https://user-images.githubusercontent.com/18099933/132632337-02f0cd7c-1e10-482c-965f-b2884220f60d.png)

**Comment by Binyang2014** [comment]
@DC-y Can you click the task retries and put the reason of retries here? We retry the job automatically if it caused by system failure, such as worker lost, k8s error...

**Comment by DC-y** [comment]
Hi, @Binyang2014 , thanks your feedback,  
As follow showing,  It will  retry always, how can I make it do not retry.
![202199-17050](https://user-images.githubusercontent.com/18099933/132656409-0f4b39de-60a9-4a2a-a8cb-6c1d7574d562.png)

```
[Exit Spec]

code: 137
phrase: ContainerSigKillReceived
issuer: PAI_OS
causer: PAI_OS
type: PLATFORM_FAILURE
stage: RUNNING
behavior: TRANSIENT
reaction: ALWAYS_RETRY
reason: 'Container killed by OS Signal: SIGKILL'
repro:
  - Kill container process by SIGKILL
solution:
  - Wait result from next retry
  - Contact Cluster Admin
pattern:
  runtimeContainerPatterns:
    - exitCode: 137
```
