### ISSUE TITLE
[Jupyter Extension Feedback]

### ISSUE THREAD

**Issue by dunzic** [microsoft/pai#5626]
Whether to provide a new version of the adaptation update

**Comment by siaimes** [comment]
OpenPAI provides the feature of custom reserved ports, which can solve this issue.

```yaml
protocolVersion: 2
name: siaimes_f83daa2b
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'openpai/standard:python_3.6-pytorch_1.4.0-gpu'
    name: docker_image_0
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 0
      cpu: 1
      memoryMB: 4096
      ports:
        Jupyter: 1
    commands:
      - pip install jupyterlab
      - >-
        jupyter-lab --ip 0.0.0.0 --port $PAI_PORT_LIST_taskrole_0_Jupyter --allow-root &
      - sleep 1d
defaults:
  virtualCluster: default
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
        userssh:
          type: custom
          value: ''
  hivedScheduler:
    taskRoles:
      taskrole:
        skuNum: 1
        skuType: cpu-machine
```

Use this configuration file to start a job, you will see the Jupyter port on the job page.
![image](https://user-images.githubusercontent.com/34199488/136678818-dcec4a6c-2b18-4a6b-8136-fd46519ec8ed.png)

Then, use `IP:Jupyter_port` in the browser to access Jupyter. If it needs authentication, you can go to stdout or stderr to find the token.

Please note that with the above information, anyone can get your files through the browser.

One way to prevent others from getting the token is to log in to the container and run this command after the job starts:
```bash
jupyter-lab --ip 0.0.0.0 --port $PAI_PORT_LIST_taskrole_0_Jupyter --allow-root &
```
