### ISSUE TITLE
How to set port in layout.yaml under directory <pai-code-dir>/contrib/kubespray/config

### ISSUE THREAD

**Issue by RomanShen** [Microsoft/pai#5634]
I am using ssh to access different servers with different port numbers. The machine-list part of layout.yaml can only specify the hostip and /bin/bash quick-start-kubespray.sh test ssh using default 22 port. How can I specify the port number in layout.yaml so that ssh test can be passed? Thanks for any advice!

```
# GPU cluster example
# This is a cluster with one master node and two worker nodes

machine-sku:
  master-machine: # define a machine sku
    # the resource requirements for all the machines of this sku
    # We use the same memory format as Kubernetes, e.g. Gi, Mi
    # Reference: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory
    mem: 60Gi
    cpu:
      # the number of CPU vcores
      vcore: 24

machine-list:
  - hostname: pai-master # name of the machine, **do not** use upper case alphabet letters for hostname
    hostip: 10.0.0.1
    machine-type: master-machine # only one master-machine supported
    pai-master: "true"
    port: 11020  # for example, I need to use port 11020 to access pai-master using ssh. Currently, it doesn't work.
```
