### ISSUE TITLE
How to submit jobs without web-portal? Just use the rest-server?

### ISSUE THREAD

**Issue by JohanOu** [microsoft/pai#5643]
**Short summary about the issue/question**:
I want to submit some jobs with different JobPriority using rest-server directly,how to use the rest api to do?Could you give me some hints? Thanks!

**Brief what process you are following**:

**OpenPAI Environment**:
- OpenPAI version:v1.8.0

**Comment by JohanOu** [comment]
In detail,how to edit the yaml to submit job if i want to adapt the JobPriority?

**Comment by Binyang2014** [comment]
```yaml
extras:
  hivedScheduler:
    jobPriorityClass: oppo
    taskRoles:
      taskrole:
        skuNum: 8
        skuType: V100
```
Here is a example. Please add hived config in extra field. And change the sku according  to your cluster
