### ISSUE TITLE
base-image, hadoop-run is not properly tagged, so can't push to registry

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#747]
For example, here's your `services-configuration.yaml`:
```
cluster:
 ...
  docker-registry-info:
    docker-namespace: openpai
    docker-registry-domain: docker.io
    docker-tag: your-tag
```

Then the base-image should be tagged as `openpai/base-image:your-tag`, but it is `base-image:latest`.
And the same as `hadoop-run`.
