### ISSUE TITLE
Duplicated hostname in cluster will lead to k8s install failure

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#795]
I generated a `cluster-configuration.yaml` as below.
```
...
machine-list:
  - hostname: ubuntu
    hostip: 10.11.3.2
    machine-type: GENERIC
    k8s-role: master
    etcdid: etcdid1
    zkid: "1"
    dashboard: "true"
    pai-master: "true"
    watchdog: "true"
  - hostname: ubuntu
    hostip: 10.11.3.4
    machine-type: GENERIC
    etcdid: etcdid2
    k8s-role: master
    node-exporter: "true"
...
```

Then the master node 10.11.3.2 was not installed any component, because the hostname 'ubuntu' is not unique in the cluster.
After fix the hostname, it works.
