### ISSUE TITLE
UI bug: dashboard has several Main menu. 

### ISSUE THREAD

**Issue by qinchen123** [Microsoft/pai#916]
Please check the screenshot.
![uibug](https://user-images.githubusercontent.com/30992872/42870260-eac60cd8-8aa9-11e8-8a06-2d8de20b62a9.PNG)

repro steps:
click -> Dashboards->home ->dashboards->home>dashboards->home

**Comment by Gerhut** [comment]
@YitongFeng Please config `root_url` with suffix `/grafana` by setting environment variable `GF_SERVER_ROOT_URL` of docker container.

Reference:
- [Running Grafana behind a reverse proxy](http://docs.grafana.org/installation/behind_proxy/#running-grafana-behind-a-reverse-proxy)
- [Configuration](http://docs.grafana.org/installation/configuration/#root-url)
- [Installing using Docker](http://docs.grafana.org/installation/docker/#configuration)

**Comment by YitongFeng** [comment]
@Gerhut 's method works, and I deployed grafana at int bed http://10.151.40.234/dashboard.html , it fix qingcha's issue, but occurs another issue: if we don't use pylon to access dashboard http://10.151.40.234:9286/dashboard.html , it can't show grafana.

@hwuu suggested that we shouldn't let services rely on pylon, for we can remove pylon anytime if needed. So we should figure out a better way to solve this issue?

**Comment by fanyangCS** [comment]
@YitongFeng , yes, grafana shouldn't rely on pylon.

**Comment by Gerhut** [comment]
Link of `Dashboards -> Home` is configured in

https://github.com/grafana/grafana/blob/v4.6.3/pkg/api/index.go#L88

which comes from `setting.AppSubUrl`, calculated from Grafana's `root_url` global configuration.

https://github.com/grafana/grafana/blob/v4.6.3/pkg/setting/setting.go#L190-L204

At present, when `root_url` is set in either config file or environment variable, it cannot be changed during the runtime, by our request URL in the browser.

So assume that we can only view Grafana from webportal, we can unified the uri of grafana in webportal and grafana, or, either environment configs works:

```yaml
- webportal:
    - GRAFANA_URI: `http://hostname:3000/`
- grafana:
    - GF_SERVER_ROOT_URL: `http://hostname:3000/` # Current, default
```

or

```yaml
- webportal:
    - GRAFANA_URI: `http://hostname/grafana` # Configs in this issue
- grafana:
    - GF_SERVER_ROOT_URL: `http://hostname/grafana` # Which I recommends
```

If we need to support both `http://host/grafana/` and `http://host:3000/` works at the runtime, perhaps we should write a customize Grafana plugin to mock it?
